// 이 파일은 tools/import_data.py 가 생성한다. 직접 고치지 말 것.
// 출처: savage13/cooking (야생의 숨결, BSD 2-Clause), Echocolat/TOTK-Cooking-Calculator (왕국의 눈물)
(function (root) {
  const ZDATA = {"EFFECTS":{"LifeMaxUp":{"prefix":"맥스","en":"Hearty","ko":"MAX 하트","icon":"💛","rate":1.0,"min":4,"max":108},"StaminaRecover":{"prefix":"원기","en":"Energizing","ko":"스태미나 회복","icon":"🟢","rate":1.399999976158142,"min":1,"max":15},"ExStaminaMaxUp":{"prefix":"스태미나","en":"Enduring","ko":"MAX 스태미나","icon":"🟡","rate":0.5,"min":1,"max":20},"ResistHot":{"prefix":"썰렁","en":"Chilly","ko":"더위 가드","icon":"❄️","rate":0.3499999940395355,"baseTime":120,"min":1,"max":2},"ResistCold":{"prefix":"화끈","en":"Spicy","ko":"추위 가드","icon":"🔥","rate":0.3499999940395355,"baseTime":120,"min":1,"max":2},"ResistElectric":{"prefix":"일렉트로","en":"Electro","ko":"전기 가드","icon":"⚡","rate":0.5,"baseTime":120,"min":1,"max":3},"AllSpeed":{"prefix":"고고","en":"Hasty","ko":"이동력 업","icon":"👟","rate":0.44999998807907104,"baseTime":30,"min":1,"max":3},"AttackUp":{"prefix":"파워","en":"Mighty","ko":"공격력 업","icon":"⚔️","rate":0.44999998807907104,"baseTime":20,"min":1,"max":3},"DefenseUp":{"prefix":"튼튼","en":"Tough","ko":"방어 업","icon":"🛡️","rate":0.44999998807907104,"baseTime":20,"min":1,"max":3},"QuietnessUp":{"prefix":"은밀","en":"Sneaky","ko":"조용함 업","icon":"🌙","rate":0.3499999940395355,"baseTime":90,"min":1,"max":3},"ResistBurn":{"prefix":"방염","en":"Fireproof","ko":"불꽃 가드","icon":"🧯","rate":0.30000001192092896,"baseTime":120,"min":1,"max":2},"LifeRepair":{"prefix":"정화","en":"Sunny","ko":"독기 대미지 회복","icon":"☀️","rate":1.0,"min":4,"max":108},"LightEmission":{"prefix":"등불","en":"Bright","ko":"발광","icon":"💡","rate":0.44999998807907104,"baseTime":90,"min":1,"max":3},"NotSlippy":{"prefix":"논슬립","en":"Sticky","ko":"미끄럼 경감","icon":"🦎","rate":0.44999998807907104,"baseTime":90,"min":1,"max":3},"SwimSpeedUp":{"prefix":"스위밍","en":"Rapid","ko":"헤엄 스피드 업","icon":"🌊","rate":0.3499999940395355,"baseTime":90,"min":1,"max":3},"AttackUpCold":{"prefix":"깡깡","en":"Biting","ko":"저온 시 냉기 공격","icon":"🧊","rate":0.3499999940395355,"baseTime":30,"min":1,"max":3},"AttackUpHot":{"prefix":"이글이글","en":"Scorching","ko":"고온 시 화염 공격","icon":"🌋","rate":0.3499999940395355,"baseTime":30,"min":1,"max":3},"AttackUpThunderstorm":{"prefix":"우르릉","en":"Stormy","ko":"뇌우 시 전기 공격","icon":"🌩️","rate":0.3499999940395355,"baseTime":30,"min":1,"max":3},"MiasmaGuard":{"prefix":"항독","en":"Warding","ko":"독기 가드","icon":"🟣","rate":1.0,"baseTime":120,"min":1,"max":3}},"TAG_KO":{"CookFruit":"과일류","CookMushroom":"버섯류","CookPlant":"채소·약초류","CookMeat":"육류","CookFish":"어패류","CookSpice":"조미료","CookInsect":"벌레류","CookEnemy":"몬스터 부위","CookOre":"광석","CookOther":"요정","CookGolem":"조나우 부품","CookForeign":"기타 소재"},"GAMES":{"botw":{"materials":[{"id":"Item_Fruit_D","en":"Hearty Durian","ko":"맥스두리안","cat":"fruit","tag":"CookFruit","hp":12,"eff":"LifeMaxUp","pot":16},
{"id":"Item_Fruit_G","en":"Palm Fruit","ko":"야자열매","cat":"fruit","tag":"CookFruit","hp":4},
{"id":"Item_Fruit_A","en":"Apple","ko":"사과","cat":"fruit","tag":"CookFruit","hp":2},
{"id":"Item_Fruit_B","en":"Wildberry","ko":"딸기","cat":"fruit","tag":"CookFruit","hp":2},
{"id":"Item_Fruit_F","en":"Hydromelon","ko":"썰렁멜론","cat":"fruit","tag":"CookFruit","hp":2,"eff":"ResistHot","pot":1},
{"id":"Item_Fruit_I","en":"Spicy Pepper","ko":"따끈따끈초 열매","cat":"fruit","tag":"CookFruit","hp":2,"eff":"ResistCold","pot":1},
{"id":"Item_Fruit_C","en":"Voltfruit","ko":"찌릿찌릿프루트","cat":"fruit","tag":"CookFruit","hp":2,"eff":"ResistElectric","pot":1},
{"id":"Item_Fruit_E","en":"Fleet-Lotus Seeds","ko":"고고연꽃 열매","cat":"fruit","tag":"CookFruit","hp":2,"eff":"AllSpeed","pot":2},
{"id":"Item_Fruit_H","en":"Mighty Bananas","ko":"칼날바나나","cat":"fruit","tag":"CookFruit","hp":2,"eff":"AttackUp","pot":2},
{"id":"Item_Mushroom_N","en":"Big Hearty Truffle","ko":"큰맥스트러플","cat":"mushroom","tag":"CookMushroom","hp":12,"eff":"LifeMaxUp","pot":16},
{"id":"Item_Mushroom_F","en":"Hearty Truffle","ko":"맥스트러플","cat":"mushroom","tag":"CookMushroom","hp":8,"eff":"LifeMaxUp","pot":4},
{"id":"Item_Mushroom_O","en":"Endura Shroom","ko":"활력버섯","cat":"mushroom","tag":"CookMushroom","hp":4,"eff":"ExStaminaMaxUp","pot":1},
{"id":"Item_Mushroom_E","en":"Hylian Shroom","ko":"하이랄버섯","cat":"mushroom","tag":"CookMushroom","hp":2},
{"id":"Item_Mushroom_A","en":"Stamella Shroom","ko":"원기버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"StaminaRecover","pot":1},
{"id":"Item_Mushroom_B","en":"Chillshroom","ko":"썰렁버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"ResistHot","pot":2},
{"id":"Item_Mushroom_C","en":"Sunshroom","ko":"따끈따끈버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"ResistCold","pot":2},
{"id":"Item_Mushroom_H","en":"Zapshroom","ko":"찌릿찌릿버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"ResistElectric","pot":2},
{"id":"Item_MushroomGet_D","en":"Rushroom","ko":"고고버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"AllSpeed","pot":1},
{"id":"Item_Mushroom_L","en":"Razorshroom","ko":"칼날버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"AttackUp","pot":2},
{"id":"Item_Mushroom_M","en":"Ironshroom","ko":"갑옷버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"DefenseUp","pot":2},
{"id":"Item_Mushroom_J","en":"Silent Shroom","ko":"은밀버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"QuietnessUp","pot":2},
{"id":"Item_PlantGet_C","en":"Big Hearty Radish","ko":"큰맥스순무","cat":"veg","tag":"CookPlant","hp":16,"eff":"LifeMaxUp","pot":20},
{"id":"Item_PlantGet_B","en":"Hearty Radish","ko":"맥스순무","cat":"veg","tag":"CookPlant","hp":10,"eff":"LifeMaxUp","pot":12},
{"id":"Item_PlantGet_Q","en":"Endura Carrot","ko":"활력당근","cat":"veg","tag":"CookPlant","hp":8,"eff":"ExStaminaMaxUp","pot":4,"base":10},
{"id":"Item_PlantGet_A","en":"Hyrule Herb","ko":"하이랄초","cat":"veg","tag":"CookPlant","hp":4},
{"id":"Item_PlantGet_M","en":"Swift Carrot","ko":"고고당근","cat":"veg","tag":"CookPlant","hp":2,"eff":"AllSpeed","pot":1},
{"id":"Item_Fruit_J","en":"Fortified Pumpkin","ko":"갑옷호박","cat":"veg","tag":"CookPlant","hp":2,"eff":"DefenseUp","pot":2},
{"id":"Item_PlantGet_E","en":"Cool Safflina","ko":"썰렁허브","cat":"veg","tag":"CookPlant","eff":"ResistHot","pot":1},
{"id":"Item_PlantGet_F","en":"Warm Safflina","ko":"따끈따끈허브","cat":"veg","tag":"CookPlant","eff":"ResistCold","pot":1},
{"id":"Item_PlantGet_L","en":"Electric Safflina","ko":"찌릿찌릿허브","cat":"veg","tag":"CookPlant","eff":"ResistElectric","pot":1},
{"id":"Item_PlantGet_O","en":"Swift Violet","ko":"고고제비꽃","cat":"veg","tag":"CookPlant","eff":"AllSpeed","pot":2},
{"id":"Item_PlantGet_G","en":"Mighty Thistle","ko":"칼날초","cat":"veg","tag":"CookPlant","eff":"AttackUp","pot":1},
{"id":"Item_PlantGet_H","en":"Armoranth","ko":"갑옷초","cat":"veg","tag":"CookPlant","eff":"DefenseUp","pot":1},
{"id":"Item_PlantGet_I","en":"Blue Nightshade","ko":"은밀초","cat":"veg","tag":"CookPlant","eff":"QuietnessUp","pot":1},
{"id":"Item_PlantGet_J","en":"Silent Princess","ko":"고요한 공주","cat":"veg","tag":"CookPlant","hp":4,"eff":"QuietnessUp","pot":3},
{"id":"Item_Meat_11","en":"Raw Gourmet Meat","ko":"특급 짐승 고기","cat":"meat","tag":"CookMeat","hp":12},
{"id":"Item_Meat_12","en":"Raw Whole Bird","ko":"특급 새 고기","cat":"meat","tag":"CookMeat","hp":12},
{"id":"Item_Meat_02","en":"Raw Prime Meat","ko":"상급 짐승 고기","cat":"meat","tag":"CookMeat","hp":6},
{"id":"Item_Meat_07","en":"Raw Bird Thigh","ko":"상급 새 고기","cat":"meat","tag":"CookMeat","hp":6},
{"id":"Item_Meat_01","en":"Raw Meat","ko":"짐승 고기","cat":"meat","tag":"CookMeat","hp":4},
{"id":"Item_Meat_06","en":"Raw Bird Drumstick","ko":"새 고기","cat":"meat","tag":"CookMeat","hp":4},
{"id":"BeeHome","en":"Courser Bee Honey","ko":"원기벌의 벌꿀","cat":"other","tag":"CookSpice","hp":8,"eff":"StaminaRecover","pot":2},
{"id":"Item_Material_03","en":"Hylian Rice","ko":"하이랄 쌀","cat":"other","tag":"CookSpice","hp":4,"sTime":30},
{"id":"Item_Material_04","en":"Bird Egg","ko":"새의 알","cat":"other","tag":"CookSpice","hp":4,"sTime":60,"crit":10},
{"id":"Item_Material_07","en":"Tabantha Wheat","ko":"타반타 밀","cat":"other","tag":"CookSpice","hp":4,"sTime":30},
{"id":"Item_Material_05","en":"Fresh Milk","ko":"신선 우유","cat":"other","tag":"CookSpice","hp":2,"sTime":50},
{"id":"Item_Fruit_K","en":"Acorn","ko":"도토리","cat":"other","tag":"CookSpice","hp":1,"sHp":2,"sTime":20},
{"id":"Item_Fruit_L","en":"Chickaloo Tree Nut","ko":"작은 새 나무 열매","cat":"other","tag":"CookSpice","hp":1,"sHp":2,"sTime":10},
{"id":"Item_Material_01","en":"Cane Sugar","ko":"사탕수수","cat":"other","tag":"CookSpice","sTime":50,"crit":30},
{"id":"Item_Material_06","en":"Goat Butter","ko":"염소 버터","cat":"other","tag":"CookSpice","sTime":50,"crit":10},
{"id":"Item_Material_02","en":"Goron Spice","ko":"고론의 향신료","cat":"other","tag":"CookSpice","sTime":60,"crit":10},
{"id":"Item_Ore_H","en":"Rock Salt","ko":"암염","cat":"other","tag":"CookSpice","sTime":30},
{"id":"Item_Material_08","en":"Monster Extract","ko":"몬스터엑기스","cat":"other","tag":"CookSpice","base":0},
{"id":"Item_Ore_J","en":"Star Fragment","ko":"별의 조각","cat":"special","tag":"CookSpice","sTime":60,"crit":100},
{"id":"Item_Enemy_38","en":"Dinraal's Scale","ko":"올드래곤의 비늘","cat":"special","tag":"CookSpice","sHp":5,"sTime":60,"crit":100},
{"id":"Item_Enemy_39","en":"Dinraal's Claw","ko":"올드래곤의 발톱","cat":"special","tag":"CookSpice","sHp":8,"sTime":180,"crit":100},
{"id":"Item_Enemy_47","en":"Shard of Dinraal's Fang","ko":"올드래곤의 이빨 조각","cat":"special","tag":"CookSpice","sHp":10,"sTime":600,"crit":100},
{"id":"Item_Enemy_48","en":"Shard of Dinraal's Horn","ko":"올드래곤의 뿔 조각","cat":"special","tag":"CookSpice","sHp":15,"sTime":1800,"crit":100},
{"id":"Item_Enemy_49","en":"Naydra's Scale","ko":"넬드래곤의 비늘","cat":"special","tag":"CookSpice","sHp":5,"sTime":60,"crit":100},
{"id":"Item_Enemy_50","en":"Naydra's Claw","ko":"넬드래곤의 발톱","cat":"special","tag":"CookSpice","sHp":8,"sTime":180,"crit":100},
{"id":"Item_Enemy_51","en":"Shard of Naydra's Fang","ko":"넬드래곤의 이빨 조각","cat":"special","tag":"CookSpice","sHp":10,"sTime":600,"crit":100},
{"id":"Item_Enemy_52","en":"Shard of Naydra's Horn","ko":"넬드래곤의 뿔 조각","cat":"special","tag":"CookSpice","sHp":15,"sTime":1800,"crit":100},
{"id":"Item_Enemy_53","en":"Farosh's Scale","ko":"필로드래곤의 비늘","cat":"special","tag":"CookSpice","sHp":5,"sTime":60,"crit":100},
{"id":"Item_Enemy_54","en":"Farosh's Claw","ko":"필로드래곤의 발톱","cat":"special","tag":"CookSpice","sHp":8,"sTime":180,"crit":100},
{"id":"Item_Enemy_55","en":"Shard of Farosh's Fang","ko":"필로드래곤의 이빨 조각","cat":"special","tag":"CookSpice","sHp":10,"sTime":600,"crit":100},
{"id":"Item_Enemy_56","en":"Shard of Farosh's Horn","ko":"필로드래곤의 뿔 조각","cat":"special","tag":"CookSpice","sHp":15,"sTime":1800,"crit":100},
{"id":"Item_FishGet_I","en":"Hearty Salmon","ko":"맥스연어","cat":"fish","tag":"CookFish","hp":16,"eff":"LifeMaxUp","pot":16},
{"id":"Item_FishGet_K","en":"Hearty Blueshell Snail","ko":"맥스소라","cat":"fish","tag":"CookFish","hp":12,"eff":"LifeMaxUp","pot":12},
{"id":"Item_FishGet_B","en":"Hearty Bass","ko":"맥스배스","cat":"fish","tag":"CookFish","hp":8,"eff":"LifeMaxUp","pot":8},
{"id":"Item_FishGet_A","en":"Hyrule Bass","ko":"하이랄배스","cat":"fish","tag":"CookFish","hp":4},
{"id":"Item_FishGet_L","en":"Staminoka Bass","ko":"원기배스","cat":"fish","tag":"CookFish","hp":4,"eff":"StaminaRecover","pot":4},
{"id":"Item_FishGet_C","en":"Chillfin Trout","ko":"썰렁송어","cat":"fish","tag":"CookFish","hp":4,"eff":"ResistHot","pot":3},
{"id":"Item_FishGet_J","en":"Sizzlefin Trout","ko":"따끈따끈송어","cat":"fish","tag":"CookFish","hp":4,"eff":"ResistCold","pot":3},
{"id":"Item_FishGet_D","en":"Voltfin Trout","ko":"찌릿찌릿송어","cat":"fish","tag":"CookFish","hp":4,"eff":"ResistElectric","pot":3},
{"id":"Item_FishGet_X","en":"Stealthfin Trout","ko":"은밀송어","cat":"fish","tag":"CookFish","hp":4,"eff":"QuietnessUp","pot":2},
{"id":"Item_FishGet_E","en":"Mighty Carp","ko":"칼날잉어","cat":"fish","tag":"CookFish","hp":4,"eff":"AttackUp","pot":2},
{"id":"Item_FishGet_H","en":"Armored Carp","ko":"갑옷잉어","cat":"fish","tag":"CookFish","hp":4,"eff":"DefenseUp","pot":2},
{"id":"Item_FishGet_Z","en":"Sanke Carp","ko":"달록잉어","cat":"fish","tag":"CookFish","hp":4},
{"id":"Item_FishGet_F","en":"Mighty Porgy","ko":"칼날도미","cat":"fish","tag":"CookFish","hp":4,"eff":"AttackUp","pot":3},
{"id":"Item_FishGet_G","en":"Armored Porgy","ko":"갑옷도미","cat":"fish","tag":"CookFish","hp":4,"eff":"DefenseUp","pot":3},
{"id":"Item_FishGet_M","en":"Sneaky River Snail","ko":"은밀우렁이","cat":"fish","tag":"CookFish","hp":4,"eff":"QuietnessUp","pot":1},
{"id":"Item_InsectGet_K","en":"Razorclaw Crab","ko":"칼날게","cat":"fish","tag":"CookFish","hp":4,"eff":"AttackUp","pot":2},
{"id":"Item_InsectGet_O","en":"Ironshell Crab","ko":"갑옷게","cat":"fish","tag":"CookFish","hp":4,"eff":"DefenseUp","pot":2},
{"id":"Item_InsectGet_Z","en":"Bright-Eyed Crab","ko":"원기게","cat":"fish","tag":"CookFish","hp":4,"eff":"StaminaRecover","pot":2},
{"id":"Animal_Insect_F","en":"Fairy","ko":"요정","cat":"special","tag":"CookOther","hp":20},
{"id":"Animal_Insect_N","en":"Winterwing Butterfly","ko":"썰렁호랑나비","cat":"critter","tag":"CookInsect","eff":"ResistHot","pot":1},
{"id":"Animal_Insect_Q","en":"Summerwing Butterfly","ko":"따끈따끈호랑나비","cat":"critter","tag":"CookInsect","eff":"ResistCold","pot":1},
{"id":"Animal_Insect_R","en":"Thunderwing Butterfly","ko":"찌릿찌릿호랑나비","cat":"critter","tag":"CookInsect","eff":"ResistElectric","pot":1},
{"id":"Animal_Insect_AB","en":"Smotherwing Butterfly","ko":"방염호랑나비","cat":"critter","tag":"CookInsect","eff":"ResistBurn","pot":2},
{"id":"Animal_Insect_C","en":"Cold Darner","ko":"썰렁왕잠자리","cat":"critter","tag":"CookInsect","eff":"ResistHot","pot":2},
{"id":"Animal_Insect_T","en":"Warm Darner","ko":"따끈따끈왕잠자리","cat":"critter","tag":"CookInsect","eff":"ResistCold","pot":2},
{"id":"Animal_Insect_I","en":"Electric Darner","ko":"찌릿찌릿왕잠자리","cat":"critter","tag":"CookInsect","eff":"ResistElectric","pot":2},
{"id":"Animal_Insect_H","en":"Restless Cricket","ko":"원기메뚜기","cat":"critter","tag":"CookInsect","eff":"StaminaRecover","pot":1},
{"id":"Animal_Insect_G","en":"Bladed Rhino Beetle","ko":"칼날장수풍뎅이","cat":"critter","tag":"CookInsect","eff":"AttackUp","pot":1},
{"id":"Animal_Insect_P","en":"Rugged Rhino Beetle","ko":"갑옷장수풍뎅이","cat":"critter","tag":"CookInsect","eff":"DefenseUp","pot":1},
{"id":"Animal_Insect_AA","en":"Energetic Rhino Beetle","ko":"원기장수풍뎅이","cat":"critter","tag":"CookInsect","eff":"StaminaRecover","pot":6},
{"id":"Animal_Insect_E","en":"Sunset Firefly","ko":"고요반딧불이","cat":"critter","tag":"CookInsect","eff":"QuietnessUp","pot":1},
{"id":"Animal_Insect_A","en":"Hot-Footed Frog","ko":"고고개구리","cat":"critter","tag":"CookInsect","eff":"AllSpeed","pot":2},
{"id":"Animal_Insect_B","en":"Tireless Frog","ko":"활력개구리","cat":"critter","tag":"CookInsect","hp":8,"eff":"ExStaminaMaxUp","pot":2},
{"id":"Animal_Insect_S","en":"Hightail Lizard","ko":"고고도마뱀","cat":"critter","tag":"CookInsect","eff":"AllSpeed","pot":1},
{"id":"Animal_Insect_M","en":"Hearty Lizard","ko":"맥스도마뱀","cat":"critter","tag":"CookInsect","hp":16,"eff":"LifeMaxUp","pot":16},
{"id":"Animal_Insect_X","en":"Fireproof Lizard","ko":"방염도마뱀","cat":"critter","tag":"CookInsect","eff":"ResistBurn","pot":1},
{"id":"Item_Ore_I","en":"Flint","ko":"부싯돌","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_F","en":"Amber","ko":"호박","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_E","en":"Opal","ko":"오팔","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_G","en":"Luminous Stone","ko":"야광석","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_D","en":"Topaz","ko":"토파즈","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_B","en":"Ruby","ko":"루비","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_C","en":"Sapphire","ko":"사파이어","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_A","en":"Diamond","ko":"다이아몬드","cat":"mineral","tag":"CookOre"},
{"id":"Item_Enemy_00","en":"Bokoblin Horn","ko":"보코블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_01","en":"Bokoblin Fang","ko":"보코블린의 이빨","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_02","en":"Bokoblin Guts","ko":"보코블린의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_06","en":"Moblin Horn","ko":"모리블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_07","en":"Moblin Fang","ko":"모리블린의 이빨","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_08","en":"Moblin Guts","ko":"모리블린의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_03","en":"Lizalfos Horn","ko":"리잘포스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_04","en":"Lizalfos Talon","ko":"리잘포스의 발톱","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_05","en":"Lizalfos Tail","ko":"리잘포스의 꼬리","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_42","en":"Icy Lizalfos Tail","ko":"얼음 리잘포스의 꼬리","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_41","en":"Red Lizalfos Tail","ko":"화염 리잘포스의 꼬리","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_43","en":"Yellow Lizalfos Tail","ko":"마비 리잘포스의 꼬리","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_12","en":"Lynel Horn","ko":"라이넬의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_13","en":"Lynel Hoof","ko":"라이넬의 발굽","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_14","en":"Lynel Guts","ko":"라이넬의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_40","en":"Chuchu Jelly","ko":"츄츄젤리","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_17","en":"White Chuchu Jelly","ko":"하얀츄츄젤리","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_15","en":"Red Chuchu Jelly","ko":"빨간츄츄젤리","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_16","en":"Yellow Chuchu Jelly","ko":"노란츄츄젤리","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_18","en":"Keese Wing","ko":"키이스의 날개","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_46","en":"Ice Keese Wing","ko":"아이스 키이스의 날개","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_44","en":"Fire Keese Wing","ko":"파이어 키이스의 날개","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_45","en":"Electric Keese Wing","ko":"일렉트로 키이스의 날개","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_19","en":"Keese Eyeball","ko":"키이스의 눈알","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_20","en":"Octorok Tentacle","ko":"옥타의 다리","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_21","en":"Octorok Eyeball","ko":"옥타의 눈알","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_57","en":"Octo Balloon","ko":"옥타 풍선","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_24","en":"Molduga Fin","ko":"몰드래고의 등지느러미","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_25","en":"Molduga Guts","ko":"몰드래고의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_32","en":"Hinox Toenail","ko":"히녹스의 발톱","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_33","en":"Hinox Tooth","ko":"히녹스의 이빨","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_34","en":"Hinox Guts","ko":"히녹스의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_27","en":"Ancient Screw","ko":"고대의 나사","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_28","en":"Ancient Spring","ko":"고대의 스프링","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_26","en":"Ancient Gear","ko":"고대의 톱니","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_29","en":"Ancient Shaft","ko":"고대의 샤프트","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_30","en":"Ancient Core","ko":"고대의 코어","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_31","en":"Giant Ancient Core","ko":"고대의 거대한 코어","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Obj_FireWoodBundle","en":"Wood","ko":"장작 묶음","cat":"mineral","tag":"CookOre"}],"recipes":[{"en":"Fairy Tonic","ko":"요정의 활력수","img":"Fairy Tonic","parts":[["Animal_Insect_F"],["CookOre"],["CookInsect"],["CookEnemy"]],"kind":"fairy","bonusHp":-12},
{"en":"Fairy Tonic","ko":"요정의 활력수","img":"Fairy Tonic","parts":[["Animal_Insect_F"],["CookInsect"],["CookEnemy"]],"kind":"fairy","bonusHp":-12},
{"en":"Fairy Tonic","ko":"요정의 활력수","img":"Fairy Tonic","parts":[["Animal_Insect_F"],["CookOre","CookEnemy","CookInsect"]],"kind":"fairy","bonusHp":-12},
{"en":"Rock-Hard Food","ko":"너무 딱딱한 요리","img":"Rock-Hard Food","parts":[["CookOre"]],"kind":"rockhard"},
{"en":"Elixir","ko":"물약","img":"Elixir","parts":[["CookEnemy"],["CookInsect"]],"kind":"elixir"},
{"en":"Dubious Food","ko":"애매한 요리","img":"Dubious Food","parts":[["CookEnemy","CookInsect"]],"kind":"dubious"},
{"en":"Fruitcake","ko":"프루트케이크","img":"Fruitcake","parts":[["Item_Fruit_A","Item_Fruit_B"],["Item_Fruit_B","Item_Fruit_C","Item_Fruit_F","Item_Fruit_H","Item_Fruit_D","Item_Fruit_G","Item_Fruit_A"],["Item_Material_07"],["Item_Material_01"]],"bonusHp":4},
{"en":"Seafood Paella","ko":"해물 파에야","img":"Seafood Paella","parts":[["Item_FishGet_F","Item_FishGet_G"],["Item_FishGet_K"],["Item_Material_03"],["Item_Material_06"],["Item_Ore_H"]],"bonusHp":8},
{"en":"Monster Curry","ko":"몬스터 카레","img":"Monster Curry","parts":[["Item_Material_03"],["Item_Material_02"],["Item_Material_08"]]},
{"en":"Monster Rice Balls","ko":"몬스터 주먹밥","img":"Monster Rice Balls","parts":[["Item_Material_03"],["Item_Ore_H"],["Item_Material_08"]]},
{"en":"Monster Cake","ko":"몬스터 케이크","img":"Monster Cake","parts":[["Item_Material_07"],["Item_Material_01"],["Item_Material_08"],["Item_Material_06"]]},
{"en":"Monster Soup","ko":"몬스터수프","img":"Monster Soup","parts":[["Item_Material_07"],["Item_Material_06"],["Item_Material_05"],["Item_Material_08"]]},
{"en":"Monster Stew","ko":"몬스터전골","img":"Monster Stew","parts":[["Item_Material_08"],["CookMeat"],["CookFish"]]},
{"en":"Creamy Heart Soup","ko":"하트 밀크수프","img":"Creamy Heart Soup","parts":[["Item_PlantGet_B","Item_PlantGet_C"],["Item_Fruit_C"],["Item_Fruit_F"],["Item_Material_05"]]},
{"en":"Clam Chowder","ko":"조개 차우더","img":"Clam Chowder","parts":[["Item_FishGet_K"],["Item_Material_07"],["Item_Material_05"],["Item_Material_06"]]},
{"en":"Pumpkin Stew","ko":"호박 스튜","img":"Pumpkin Stew","parts":[["Item_Fruit_J"],["Item_Material_07"],["Item_Material_05"],["Item_Material_06"]]},
{"en":"Gourmet Meat Stew","ko":"특급 고기 스튜","img":"Gourmet Meat Stew","parts":[["Item_Meat_11","Item_Meat_12"],["Item_Material_07"],["Item_Material_05"],["Item_Material_06"]]},
{"en":"Prime Meat Stew","ko":"상급 고기 스튜","img":"Prime Meat Stew","parts":[["Item_Meat_02","Item_Meat_07"],["Item_Material_07"],["Item_Material_05"],["Item_Material_06"]]},
{"en":"Meat Stew","ko":"고기 스튜","img":"Meat Stew","parts":[["Item_Meat_01","Item_Meat_06"],["Item_Material_07"],["Item_Material_05"],["Item_Material_06"]]},
{"en":"Gourmet Meat Curry","ko":"특급 고기 카레","img":"Gourmet Meat Curry","parts":[["Item_Meat_11"],["Item_Material_03"],["Item_Material_02"]]},
{"en":"Gourmet Poultry Curry","ko":"특급 치킨 카레","img":"Gourmet Poultry Curry","parts":[["Item_Meat_12"],["Item_Material_03"],["Item_Material_02"]]},
{"en":"Prime Meat Curry","ko":"상급 고기 카레","img":"Prime Meat Curry","parts":[["Item_Meat_02"],["Item_Material_03"],["Item_Material_02"]]},
{"en":"Prime Poultry Curry","ko":"상급 치킨 카레","img":"Prime Poultry Curry","parts":[["Item_Meat_07"],["Item_Material_03"],["Item_Material_02"]]},
{"en":"Meat Curry","ko":"짐승 고기 카레","img":"Meat Curry","parts":[["Item_Meat_01"],["Item_Material_03"],["Item_Material_02"]]},
{"en":"Poultry Curry","ko":"치킨 카레","img":"Poultry Curry","parts":[["Item_Meat_06"],["Item_Material_03"],["Item_Material_02"]]},
{"en":"Seafood Curry","ko":"해산물 카레","img":"Seafood Curry","parts":[["Item_FishGet_K","Item_FishGet_F","Item_FishGet_G"],["Item_Material_03"],["Item_Material_02"]]},
{"en":"Vegetable Curry","ko":"야채 카레","img":"Vegetable Curry","parts":[["Item_Fruit_J","Item_PlantGet_M","Item_PlantGet_Q"],["Item_Material_03"],["Item_Material_02"]]},
{"en":"Pumpkin Pie","ko":"호박 케이크","img":"Pumpkin Pie","parts":[["Item_Fruit_J"],["Item_Material_07"],["Item_Material_01"],["Item_Material_06"]]},
{"en":"Carrot Cake","ko":"당근 케이크","img":"Carrot Cake","parts":[["Item_PlantGet_M","Item_PlantGet_Q"],["Item_Material_07"],["Item_Material_01"],["Item_Material_06"]]},
{"en":"Wildberry Crepe","ko":"딸기 크레이프","img":"Wildberry Crepe","parts":[["Item_Material_07"],["Item_Material_05"],["Item_Material_04"],["Item_Material_01"],["Item_Fruit_B"]],"bonusHp":16},
{"en":"Honey Crepe","ko":"벌꿀 크레이프","img":"Honey Crepe","parts":[["Item_Material_07"],["Item_Material_05"],["Item_Material_04"],["Item_Material_01"],["BeeHome"]],"bonusHp":4},
{"en":"Plain Crepe","ko":"플레인 크레이프","img":"Plain Crepe","parts":[["Item_Material_07"],["Item_Material_05"],["Item_Material_04"],["Item_Material_01"]]},
{"en":"Apple Pie","ko":"애플파이","img":"Apple Pie","parts":[["Item_Fruit_A"],["Item_Material_07"],["Item_Material_06"],["Item_Material_01"]]},
{"en":"Nutcake","ko":"너츠 케이크","img":"Nutcake","parts":[["Item_Material_07"],["Item_Material_06"],["Item_Material_01"],["Item_Fruit_L","Item_Fruit_K"]]},
{"en":"Egg Tart","ko":"에그 타르트","img":"Egg Tart","parts":[["Item_Material_04"],["Item_Material_07"],["Item_Material_06"],["Item_Material_01"]]},
{"en":"Egg Pudding","ko":"달걀 푸딩","img":"Egg Pudding","parts":[["Item_Material_04"],["Item_Material_05"],["Item_Material_01"]]},
{"en":"Fried Bananas","ko":"튀긴 바나나","img":"Fried Bananas","parts":[["Item_Fruit_H"],["Item_Material_07"],["Item_Material_01"]]},
{"en":"Fruit Pie","ko":"프루트 파이","img":"Fruit Pie","parts":[["Item_Material_07"],["Item_Material_06"],["Item_Material_01"],["CookFruit"]]},
{"en":"Meat Pie","ko":"미트 파이","img":"Meat Pie","parts":[["Item_Material_07"],["Item_Material_06"],["Item_Ore_H"],["CookMeat"]]},
{"en":"Fish Pie","ko":"피시 파이","img":"Fish Pie","parts":[["Item_Material_07"],["Item_Material_06"],["Item_Ore_H"],["CookFish"]]},
{"en":"Salmon Meunière","ko":"연어 뫼니에르","img":"Salmon Meunière","parts":[["Item_FishGet_I"],["Item_Material_06"],["Item_Material_07"]]},
{"en":"Salmon Risotto","ko":"연어 리조또","img":"Salmon Risotto","parts":[["Item_FishGet_I"],["Item_Material_03"],["Item_Ore_H"],["Item_Material_06"]]},
{"en":"Crab Risotto","ko":"게살 리조또","img":"Crab Risotto","parts":[["Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"],["Item_Material_03"],["Item_Ore_H"],["Item_Material_06"]]},
{"en":"Vegetable Risotto","ko":"야채 리조또","img":"Vegetable Risotto","parts":[["Item_Fruit_J","Item_PlantGet_M","Item_PlantGet_Q"],["Item_Material_03"],["Item_Ore_H"],["Item_Material_06"]]},
{"en":"Mushroom Risotto","ko":"버섯 리조또","img":"Mushroom Risotto","parts":[["Item_Material_03"],["Item_Ore_H"],["Item_Material_06"],["CookMushroom"]]},
{"en":"Cream of Mushroom Soup","ko":"버섯 밀크수프","img":"Cream of Mushroom Soup","parts":[["Item_Ore_H"],["Item_Material_05"],["CookMushroom"],["CookPlant"]]},
{"en":"Veggie Cream Soup","ko":"야채 크림수프","img":"Veggie Cream Soup","parts":[["Item_Fruit_J","Item_PlantGet_M","Item_PlantGet_Q"],["Item_Ore_H"],["Item_Material_05"]]},
{"en":"Creamy Meat Soup","ko":"고기 밀크수프","img":"Creamy Meat Soup","parts":[["Item_Ore_H"],["Item_Material_05"],["CookMeat"],["CookPlant"]]},
{"en":"Creamy Seafood Soup","ko":"생선 밀크수프","img":"Creamy Seafood Soup","parts":[["Item_Ore_H"],["Item_Material_05"],["CookFish"],["CookPlant"]]},
{"en":"Cream of Vegetable Soup","ko":"야채 밀크수프","img":"Cream of Vegetable Soup","parts":[["Item_Ore_H"],["Item_Material_05"],["CookPlant"]]},
{"en":"Carrot Stew","ko":"당근 스튜","img":"Carrot Stew","parts":[["Item_PlantGet_M","Item_PlantGet_Q"],["Item_Material_06"],["Item_Material_05"],["Item_Material_07"]]},
{"en":"Mushroom Omelet","ko":"버섯 오믈렛","img":"Mushroom Omelet","parts":[["Item_Material_04"],["Item_Ore_H"],["Item_Material_06"],["CookMushroom"]]},
{"en":"Crab Omelet with Rice","ko":"게살 달걀볶음밥","img":"Crab Omelet with Rice","parts":[["Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"],["Item_Material_04"],["Item_Material_03"],["Item_Ore_H"]]},
{"en":"Gourmet Poultry Pilaf","ko":"특급 치킨 필래프","img":"Gourmet Poultry Pilaf","parts":[["Item_Meat_12"],["Item_Material_04"],["Item_Material_03"],["Item_Material_06"]]},
{"en":"Prime Poultry Pilaf","ko":"상급 치킨 필래프","img":"Prime Poultry Pilaf","parts":[["Item_Meat_07"],["Item_Material_04"],["Item_Material_03"],["Item_Material_06"]]},
{"en":"Poultry Pilaf","ko":"치킨 필래프","img":"Poultry Pilaf","parts":[["Item_Meat_06"],["Item_Material_04"],["Item_Material_03"],["Item_Material_06"]]},
{"en":"Vegetable Omelet","ko":"야채 오믈렛","img":"Vegetable Omelet","parts":[["Item_Material_04"],["Item_Material_06"],["Item_Ore_H"],["CookPlant"]]},
{"en":"Porgy Meunière","ko":"도미 뫼니에르","img":"Porgy Meunière","parts":[["Item_FishGet_F","Item_FishGet_G"],["Item_Material_06"],["Item_Material_07"]]},
{"en":"Seafood Meunière","ko":"생선 뫼니에르","img":"Seafood Meunière","parts":[["Item_Material_06"],["Item_Material_07"],["CookFish"]]},
{"en":"Seafood Fried Rice","ko":"해물볶음밥","img":"Seafood Fried Rice","parts":[["Item_FishGet_K","Item_FishGet_F","Item_FishGet_G"],["Item_Material_03"],["Item_Ore_H"]]},
{"en":"Curry Pilaf","ko":"카레 필래프","img":"Curry Pilaf","parts":[["Item_Material_02"],["Item_Material_03"],["Item_Material_06"]]},
{"en":"Gourmet Meat and Rice Bowl","ko":"특급 짐승 고기덮밥","img":"Gourmet Meat and Rice Bowl","parts":[["Item_Meat_11"],["Item_Material_03"],["Item_Ore_H"]]},
{"en":"Prime Meat and Rice Bowl","ko":"상급 짐승 고기덮밥","img":"Prime Meat and Rice Bowl","parts":[["Item_Meat_02"],["Item_Material_03"],["Item_Ore_H"]]},
{"en":"Meat and Rice Bowl","ko":"짐승 고기덮밥","img":"Meat and Rice Bowl","parts":[["Item_Meat_01"],["Item_Material_03"],["Item_Ore_H"]]},
{"en":"Fried Egg and Rice","ko":"달걀프라이라이스","img":"Fried Egg and Rice","parts":[["Item_Material_03"],["Item_Material_04"]]},
{"en":"Meaty Rice Balls","ko":"고기 주먹밥","img":"Meaty Rice Balls","parts":[["Item_Material_03"],["CookMeat"]]},
{"en":"Seafood Rice Balls","ko":"해물 주먹밥","img":"Seafood Rice Balls","parts":[["Item_Material_03"],["CookFish"]]},
{"en":"Mushroom Rice Balls","ko":"버섯 주먹밥","img":"Mushroom Rice Balls","parts":[["Item_Material_03"],["CookMushroom"]]},
{"en":"Veggie Rice Balls","ko":"야채 주먹밥","img":"Veggie Rice Balls","parts":[["Item_Material_03"],["CookPlant"]]},
{"en":"Hot Buttered Apple","ko":"버터 바른 사과","img":"Hot Buttered Apple","parts":[["Item_Fruit_A"],["Item_Material_06"]],"bonusHp":4},
{"en":"Meat-Stuffed Pumpkin","ko":"고기를 넣은 호박","img":"Meat-Stuffed Pumpkin","parts":[["Item_Fruit_J"],["CookMeat"]]},
{"en":"Glazed Meat","ko":"달게 조린 고기","img":"Glazed Meat","parts":[["BeeHome"],["CookMeat"]]},
{"en":"Glazed Seafood","ko":"달게 조린 생선","img":"Glazed Seafood","parts":[["BeeHome"],["CookFish"]]},
{"en":"Glazed Mushrooms","ko":"달게 조린 버섯","img":"Glazed Mushrooms","parts":[["BeeHome"],["CookMushroom"]]},
{"en":"Glazed Veggies","ko":"달게 조린 야채","img":"Glazed Veggies","parts":[["BeeHome"],["CookPlant"]]},
{"en":"Curry Rice","ko":"카레라이스","img":"Curry Rice","parts":[["Item_Material_03"],["Item_Material_02"]]},
{"en":"Honeyed Apple","ko":"꿀에 절인 사과","img":"Honeyed Apple","parts":[["Item_Fruit_A"],["BeeHome"]]},
{"en":"Honeyed Fruits","ko":"꿀에 절인 과일","img":"Honeyed Fruits","parts":[["BeeHome"],["CookFruit"]]},
{"en":"Gourmet Spiced Meat Skewer","ko":"특급 짐승 스테이크","img":"Gourmet Spiced Meat Skewer","parts":[["Item_Meat_11"],["Item_Material_02"]]},
{"en":"Prime Spiced Meat Skewer","ko":"상급 짐승 스테이크","img":"Prime Spiced Meat Skewer","parts":[["Item_Meat_02"],["Item_Material_02"]]},
{"en":"Spiced Meat Skewer","ko":"짐승 스테이크","img":"Spiced Meat Skewer","parts":[["Item_Meat_01"],["Item_Material_02"]]},
{"en":"Fragrant Mushroom Sauté","ko":"향긋한 버섯볶음","img":"Fragrant Mushroom Sauté","parts":[["Item_Material_02"],["CookMushroom"]]},
{"en":"Herb Sauté","ko":"향긋한 나물볶음","img":"Herb Sauté","parts":[["Item_Material_02"],["CookPlant"]]},
{"en":"Salt-Grilled Gourmet Meat","ko":"특급 고기 소금구이","img":"Salt-Grilled Gourmet Meat","parts":[["Item_Meat_11","Item_Meat_12"],["Item_Ore_H"]]},
{"en":"Salt-Grilled Prime Meat","ko":"상급 고기 소금구이","img":"Salt-Grilled Prime Meat","parts":[["Item_Meat_07","Item_Meat_02"],["Item_Ore_H"]]},
{"en":"Salt-Grilled Meat","ko":"고기 소금구이","img":"Salt-Grilled Meat","parts":[["Item_Meat_01","Item_Meat_06"],["Item_Ore_H"]]},
{"en":"Crab Stir-Fry","ko":"게볶음","img":"Crab Stir-Fry","parts":[["Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"],["Item_Material_02"]]},
{"en":"Salt-Grilled Crab","ko":"게 소금구이","img":"Salt-Grilled Crab","parts":[["Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"],["Item_Ore_H"]]},
{"en":"Salt-Grilled Fish","ko":"생선 소금구이","img":"Salt-Grilled Fish","parts":[["Item_Ore_H"],["CookFish"]]},
{"en":"Wheat Bread","ko":"밀 빵","img":"Wheat Bread","parts":[["Item_Material_07"],["Item_Ore_H"]]},
{"en":"Salt-Grilled Greens","ko":"야채 소금구이","img":"Salt-Grilled Greens","parts":[["Item_Ore_H"],["CookPlant"]]},
{"en":"Salt-Grilled Mushrooms","ko":"버섯 소금구이","img":"Salt-Grilled Mushrooms","parts":[["Item_Ore_H"],["CookMushroom"]]},
{"en":"Copious Meat Skewers","ko":"고기 꼬치구이 곱빼기","img":"Copious Meat Skewers","parts":[["CookMeat"],["CookMeat"],["CookMeat"],["CookMeat"]]},
{"en":"Copious Fried Wild Greens","ko":"야채구이 곱빼기","img":"Copious Fried Wild Greens","parts":[["CookPlant"],["CookPlant"],["CookPlant"],["CookPlant"]]},
{"en":"Copious Simmered Fruit","ko":"과일전골 곱빼기","img":"Copious Simmered Fruit","parts":[["CookFruit"],["CookFruit"],["CookFruit"],["CookFruit"]]},
{"en":"Copious Mushroom Skewers","ko":"버섯구이 곱빼기","img":"Copious Mushroom Skewers","parts":[["CookMushroom"],["CookMushroom"],["CookMushroom"],["CookMushroom"]]},
{"en":"Copious Seafood Skewers","ko":"생선 꼬치구이 곱빼기","img":"Copious Seafood Skewers","parts":[["CookFish"],["CookFish"],["CookFish"],["CookFish"]]},
{"en":"Meat Skewer","ko":"고기 꼬치구이","img":"Meat Skewer","parts":[["CookMeat"],["CookMeat"]]},
{"en":"Simmered Fruit","ko":"과일전골","img":"Simmered Fruit","parts":[["CookFruit"],["CookFruit"]]},
{"en":"Mushroom Skewer","ko":"버섯 꼬치구이","img":"Mushroom Skewer","parts":[["CookMushroom"],["CookMushroom"]]},
{"en":"Fried Wild Greens","ko":"야채구이","img":"Fried Wild Greens","parts":[["CookPlant"],["CookPlant"]]},
{"en":"Gourmet Meat and Seafood Fry","ko":"특급 고기와 생선구이","img":"Gourmet Meat and Seafood Fry","parts":[["Item_Meat_11","Item_Meat_12"],["CookFish"]]},
{"en":"Prime Meat and Seafood Fry","ko":"상급 고기와 생선구이","img":"Prime Meat and Seafood Fry","parts":[["Item_Meat_02","Item_Meat_07"],["CookFish"]]},
{"en":"Meat and Seafood Fry","ko":"고기와 생선구이","img":"Meat and Seafood Fry","parts":[["CookMeat"],["CookFish"]]},
{"en":"Pepper Steak","ko":"스파이시 고기구이","img":"Pepper Steak","parts":[["Item_Fruit_I"],["CookMeat"]]},
{"en":"Pepper Seafood","ko":"스파이시 생선구이","img":"Pepper Seafood","parts":[["Item_Fruit_I"],["CookFish"]]},
{"en":"Seafood Skewer","ko":"해산물 꼬치구이","img":"Seafood Skewer","parts":[["Item_FishGet_K","Item_FishGet_M","Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"],["CookFish"]]},
{"en":"Fish Skewer","ko":"생선 꼬치구이","img":"Fish Skewer","parts":[["CookFish"],["CookFish"]]},
{"en":"Steamed Meat","ko":"고기쌈구이","img":"Steamed Meat","parts":[["CookPlant"],["CookMeat"]]},
{"en":"Steamed Fish","ko":"생선쌈구이","img":"Steamed Fish","parts":[["CookPlant"],["CookFish"]]},
{"en":"Steamed Mushrooms","ko":"버섯쌈구이","img":"Steamed Mushrooms","parts":[["CookPlant"],["CookMushroom"]]},
{"en":"Steamed Fruit","ko":"과일찜","img":"Steamed Fruit","parts":[["CookPlant"],["CookFruit"]]},
{"en":"Fish and Mushroom Skewer","ko":"생선 꼬치구이와 버섯","img":"Fish and Mushroom Skewer","parts":[["CookMushroom"],["CookFish"]]},
{"en":"Meat and Mushroom Skewer","ko":"고기 꼬치구이와 버섯","img":"Meat and Mushroom Skewer","parts":[["CookMushroom"],["CookMeat"]]},
{"en":"Fruit and Mushroom Mix","ko":"과일 버섯무침","img":"Fruit and Mushroom Mix","parts":[["CookMushroom"],["CookFruit"]]},
{"en":"Meat Skewer","ko":"고기 꼬치구이","img":"Meat Skewer","parts":[["CookMeat"]]},
{"en":"Seafood Skewer","ko":"해산물 꼬치구이","img":"Seafood Skewer","parts":[["Item_FishGet_K","Item_FishGet_M","Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"]]},
{"en":"Fish Skewer","ko":"생선 꼬치구이","img":"Fish Skewer","parts":[["CookFish"]]},
{"en":"Omelet","ko":"오믈렛","img":"Omelet","parts":[["Item_Material_04"]]},
{"en":"Milk","ko":"핫밀크","img":"Warm Milk","parts":[["Item_Material_05"]]},
{"en":"Mushroom Skewer","ko":"버섯 꼬치구이","img":"Mushroom Skewer","parts":[["CookMushroom"]]},
{"en":"Fried Wild Greens","ko":"야채구이","img":"Fried Wild Greens","parts":[["CookPlant"]]},
{"en":"Simmered Fruit","ko":"과일전골","img":"Simmered Fruit","parts":[["CookFruit"]]},
{"en":"Sautéed Nuts","ko":"너츠볶음","img":"Sautéed Nuts","parts":[["Item_Fruit_K"],["Item_Fruit_L"]]},
{"en":"Fairy Tonic","ko":"요정의 활력수","img":"Fairy Tonic","parts":[["Animal_Insect_F"]],"kind":"fairy","bonusHp":-12}],"singles":[{"en":"Fairy Tonic","ko":"요정의 활력수","img":"Fairy Tonic","parts":[["Animal_Insect_F"]],"single":true,"kind":"fairy","bonusHp":-12},
{"en":"Rock-Hard Food","ko":"너무 딱딱한 요리","img":"Rock-Hard Food","parts":[["CookOre"]],"single":true,"kind":"rockhard"},
{"en":"Sautéed Peppers","ko":"따끈따끈볶음","img":"Sautéed Peppers","parts":[["Item_Fruit_I"]],"single":true},
{"en":"Omelet","ko":"오믈렛","img":"Omelet","parts":[["Item_Material_04"]],"single":true},
{"en":"Meat Skewer","ko":"고기 꼬치구이","img":"Meat Skewer","parts":[["CookMeat"]],"single":true},
{"en":"Seafood Skewer","ko":"해산물 꼬치구이","img":"Seafood Skewer","parts":[["Item_FishGet_K","Item_FishGet_M","Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"]],"single":true},
{"en":"Fish Skewer","ko":"생선 꼬치구이","img":"Fish Skewer","parts":[["CookFish"]],"single":true},
{"en":"Mushroom Skewer","ko":"버섯 꼬치구이","img":"Mushroom Skewer","parts":[["CookMushroom"]],"single":true},
{"en":"Honey Candy","ko":"벌꿀 사탕","img":"Honey Candy","parts":[["BeeHome"]],"single":true,"bonusHp":-8},
{"en":"Sautéed Nuts","ko":"너츠볶음","img":"Sautéed Nuts","parts":[["Item_Fruit_K","Item_Fruit_L"]],"single":true,"bonusHp":-2},
{"en":"Milk","ko":"핫밀크","img":"Warm Milk","parts":[["Item_Material_05"]],"single":true,"bonusHp":2},
{"en":"Fried Wild Greens","ko":"야채구이","img":"Fried Wild Greens","parts":[["CookPlant"]],"single":true},
{"en":"Simmered Fruit","ko":"과일전골","img":"Simmered Fruit","parts":[["CookFruit"]],"single":true}],"critByTypes":[5,10,15,20,25],"elixir":{"ko":"물약","en":"Elixir"}},"totk":{"materials":[{"id":"Item_Ore_M","en":"Large Zonaite","ko":"커다란 조나니움","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_L","en":"Zonaite","ko":"조나니움","cat":"mineral","tag":"CookOre"},
{"id":"Animal_Insect_AH","en":"Sticky Lizard","ko":"접착도마뱀","cat":"critter","tag":"CookInsect","eff":"NotSlippy","pot":1},
{"id":"Animal_Insect_X","en":"Fireproof Lizard","ko":"방염도마뱀","cat":"critter","tag":"CookInsect","eff":"ResistBurn","pot":1},
{"id":"Animal_Insect_S","en":"Hightail Lizard","ko":"고고도마뱀","cat":"critter","tag":"CookInsect","eff":"AllSpeed","pot":1},
{"id":"Animal_Insect_AG","en":"Sticky Frog","ko":"접착개구리","cat":"critter","tag":"CookInsect","eff":"NotSlippy","pot":2},
{"id":"Animal_Insect_A","en":"Hot-Footed Frog","ko":"고고개구리","cat":"critter","tag":"CookInsect","eff":"AllSpeed","pot":2},
{"id":"Item_Enemy_160","en":"Shard of Light Dragon's Fang","ko":"백룡의 이빨 조각","cat":"special","tag":"CookSpice","sHp":10,"sTime":600,"crit":100},
{"id":"Item_Enemy_55","en":"Shard of Farosh's Fang","ko":"필로드래곤의 이빨 조각","cat":"special","tag":"CookSpice","sHp":10,"sTime":600,"crit":100},
{"id":"Animal_Insect_H","en":"Restless Cricket","ko":"원기메뚜기","cat":"critter","tag":"CookInsect","eff":"StaminaRecover","pot":1},
{"id":"Item_Enemy_47","en":"Shard of Dinraal's Fang","ko":"올드래곤의 이빨 조각","cat":"special","tag":"CookSpice","sHp":10,"sTime":600,"crit":100},
{"id":"Item_Enemy_51","en":"Shard of Naydra's Fang","ko":"넬드래곤의 이빨 조각","cat":"special","tag":"CookSpice","sHp":10,"sTime":600,"crit":100},
{"id":"Animal_Insect_AI","en":"Deep Firefly","ko":"어둠반딧불이","cat":"critter","tag":"CookInsect","eff":"LightEmission","pot":2},
{"id":"Animal_Insect_E","en":"Sunset Firefly","ko":"고요반딧불이","cat":"critter","tag":"CookInsect","eff":"QuietnessUp","pot":1},
{"id":"Item_Enemy_159","en":"Light Dragon's Talon","ko":"백룡의 발톱","cat":"special","tag":"CookSpice","sHp":8,"sTime":180,"crit":100},
{"id":"Animal_Insect_P","en":"Rugged Rhino Beetle","ko":"갑옷장수풍뎅이","cat":"critter","tag":"CookInsect","eff":"DefenseUp","pot":1},
{"id":"Item_Enemy_54","en":"Farosh's Claw","ko":"필로드래곤의 발톱","cat":"special","tag":"CookSpice","sHp":8,"sTime":180,"crit":100},
{"id":"Animal_Insect_G","en":"Bladed Rhino Beetle","ko":"칼날장수풍뎅이","cat":"critter","tag":"CookInsect","eff":"AttackUp","pot":1},
{"id":"Animal_Insect_AA","en":"Energetic Rhino Beetle","ko":"원기장수풍뎅이","cat":"critter","tag":"CookInsect","eff":"StaminaRecover","pot":6},
{"id":"Item_Enemy_50","en":"Naydra's Claw","ko":"넬드래곤의 발톱","cat":"special","tag":"CookSpice","sHp":8,"sTime":180,"crit":100},
{"id":"Animal_Insect_I","en":"Electric Darner","ko":"찌릿찌릿왕잠자리","cat":"critter","tag":"CookInsect","eff":"ResistElectric","pot":2},
{"id":"Item_Enemy_39","en":"Dinraal's Claw","ko":"올드래곤의 발톱","cat":"special","tag":"CookSpice","sHp":8,"sTime":180,"crit":100},
{"id":"Animal_Insect_T","en":"Warm Darner","ko":"따끈따끈왕잠자리","cat":"critter","tag":"CookInsect","eff":"ResistCold","pot":2},
{"id":"Animal_Insect_C","en":"Cold Darner","ko":"썰렁왕잠자리","cat":"critter","tag":"CookInsect","eff":"ResistHot","pot":2},
{"id":"Item_Enemy_158","en":"Light Dragon's Scale","ko":"백룡의 비늘","cat":"special","tag":"CookSpice","sHp":5,"sTime":60,"crit":100},
{"id":"Animal_Insect_AB","en":"Smotherwing Butterfly","ko":"방염호랑나비","cat":"critter","tag":"CookInsect","eff":"ResistBurn","pot":2},
{"id":"Animal_Insect_R","en":"Thunderwing Butterfly","ko":"찌릿찌릿호랑나비","cat":"critter","tag":"CookInsect","eff":"ResistElectric","pot":1},
{"id":"Item_Enemy_53","en":"Farosh's Scale","ko":"필로드래곤의 비늘","cat":"special","tag":"CookSpice","sHp":5,"sTime":60,"crit":100},
{"id":"Animal_Insect_Q","en":"Summerwing Butterfly","ko":"따끈따끈호랑나비","cat":"critter","tag":"CookInsect","eff":"ResistCold","pot":1},
{"id":"Animal_Insect_N","en":"Winterwing Butterfly","ko":"썰렁호랑나비","cat":"critter","tag":"CookInsect","eff":"ResistHot","pot":1},
{"id":"Item_Enemy_49","en":"Naydra's Scale","ko":"넬드래곤의 비늘","cat":"special","tag":"CookSpice","sHp":5,"sTime":60,"crit":100},
{"id":"Item_Enemy_38","en":"Dinraal's Scale","ko":"올드래곤의 비늘","cat":"special","tag":"CookSpice","sHp":5,"sTime":60,"crit":100},
{"id":"Item_Enemy_189","en":"Frox Fingernail","ko":"데그가마의 발톱","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_04","en":"Lizalfos Talon","ko":"리잘포스의 발톱","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_104","en":"Horriblin Claw","ko":"호러블린의 발톱","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_33","en":"Hinox Tooth","ko":"히녹스의 이빨","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_135","en":"Boss Bokoblin Fang","ko":"보스보코블린의 이빨","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_07","en":"Moblin Fang","ko":"모리블린의 이빨","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_01","en":"Bokoblin Fang","ko":"보코블린의 이빨","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_20","en":"Octorok Tentacle","ko":"옥타의 다리","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_69","en":"Gibdo Bone","ko":"기브도의 뼈","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_231","en":"Shard of Light Dragon's Spike","ko":"백룡의 용암석","cat":"special","tag":"CookSpice","sTime":80,"crit":10},
{"id":"Item_Enemy_230","en":"Shard of Farosh's Spike","ko":"필로드래곤의 용암석","cat":"special","tag":"CookSpice","sTime":80,"crit":10},
{"id":"Item_Enemy_229","en":"Shard of Naydra's Spike","ko":"넬드래곤의 용암석","cat":"special","tag":"CookSpice","sTime":80,"crit":10},
{"id":"Item_Enemy_228","en":"Shard of Dinraal's Spike","ko":"올드래곤의 용암석","cat":"special","tag":"CookSpice","sTime":80,"crit":10},
{"id":"Item_Enemy_188","en":"Blue-White Frox Fang","ko":"창백의 데그가마의 큰 이빨","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_187","en":"Obsidian Frox Fang","ko":"흑요의 데그가마의 큰 이빨","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_186","en":"Frox Fang","ko":"데그가마의 큰 이빨","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_210","en":"Molduga Jaw","ko":"몰드래고의 턱뼈","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_208","en":"Stalnox Horn","ko":"스탈 히녹스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_144","en":"Black Hinox Horn","ko":"블랙 히녹스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_143","en":"Blue Hinox Horn","ko":"블루 히녹스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_142","en":"Hinox Horn","ko":"히녹스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_218","en":"Silver Lynel Mace Horn","ko":"실버 라이넬의 분쇄뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_217","en":"White-Maned Lynel Mace Horn","ko":"하얀 갈기의 라이넬의 분쇄뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_216","en":"Blue-Maned Lynel Mace Horn","ko":"푸른 갈기의 라이넬의 분쇄뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_215","en":"Lynel Mace Horn","ko":"라이넬의 분쇄뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_13","en":"Lynel Hoof","ko":"라이넬의 발굽","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_103","en":"Silver Horriblin Horn","ko":"실버 호러블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_102","en":"Black Horriblin Horn","ko":"블랙 호러블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_101","en":"Blue Horriblin Horn","ko":"블루 호러블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_100","en":"Horriblin Horn","ko":"호러블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_92","en":"Silver Moblin Horn","ko":"실버 모리블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_91","en":"Black Moblin Horn","ko":"블랙 모리블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_90","en":"Blue Moblin Horn","ko":"블루 모리블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_89","en":"Moblin Horn","ko":"모리블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_183","en":"Shock Like Stone","ko":"일렉트로 조아의 위돌","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_184","en":"Ice Like Stone","ko":"아이스 조아의 위돌","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_181","en":"Like Like Stone","ko":"조아조아의 위돌","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_182","en":"Fire Like Stone","ko":"파이어 조아의 위돌","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_214","en":"Light Dragon's Horn","ko":"백룡의 뿔","cat":"special","tag":"CookSpice","sHp":15,"sTime":1800,"crit":100},
{"id":"Item_Enemy_213","en":"Farosh's Horn","ko":"필로드래곤의 뿔","cat":"special","tag":"CookSpice","sHp":15,"sTime":1800,"crit":100},
{"id":"Item_Enemy_212","en":"Naydra's Horn","ko":"넬드래곤의 뿔","cat":"special","tag":"CookSpice","sHp":15,"sTime":1800,"crit":100},
{"id":"Item_Enemy_211","en":"Dinraal's Horn","ko":"올드래곤의 뿔","cat":"special","tag":"CookSpice","sHp":15,"sTime":1800,"crit":100},
{"id":"Item_Enemy_155","en":"Gleeok Thunder Horn","ko":"그리오크의 뇌전각","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_154","en":"Gleeok Frost Horn","ko":"그리오크의 빙설각","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_153","en":"Gleeok Flame Horn","ko":"그리오크의 화염각","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_32","en":"Hinox Toenail","ko":"히녹스의 발톱","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_151","en":"Silver Lynel Saber Horn","ko":"실버 라이넬의 칼날뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_150","en":"White-Maned Lynel Saber Horn","ko":"하얀 갈기의 라이넬의 칼날뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_149","en":"Blue-Maned Lynel Saber Horn","ko":"푸른 갈기의 라이넬의 칼날뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_148","en":"Lynel Saber Horn","ko":"라이넬의 칼날뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_60","en":"Electric Lizalfos Horn","ko":"마비 리잘포스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_59","en":"Ice-Breath Lizalfos Horn","ko":"얼음 리잘포스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_58","en":"Fire-Breath Lizalfos Horn","ko":"화염 리잘포스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_109","en":"Silver Lizalfos Horn","ko":"실버 리잘포스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_108","en":"Black Lizalfos Horn","ko":"블랙 리잘포스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_107","en":"Blue Lizalfos Horn","ko":"블루 리잘포스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_106","en":"Lizalfos Horn","ko":"리잘포스의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_134","en":"Silver Boss Bokoblin Horn","ko":"실버 보스보코블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_133","en":"Black Boss Bokoblin Horn","ko":"블랙 보스보코블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_132","en":"Blue Boss Bokoblin Horn","ko":"블루 보스보코블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_64","en":"Boss Bokoblin Horn","ko":"보스보코블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_80","en":"Silver Bokoblin Horn","ko":"실버 보코블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_79","en":"Black Bokoblin Horn","ko":"블랙 보코블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_78","en":"Blue Bokoblin Horn","ko":"블루 보코블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_77","en":"Bokoblin Horn","ko":"보코블린의 뿔","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_InsectGet_Z","en":"Bright-Eyed Crab","ko":"원기게","cat":"fish","tag":"CookFish","hp":4,"eff":"StaminaRecover","pot":2},
{"id":"Item_InsectGet_O","en":"Ironshell Crab","ko":"갑옷게","cat":"fish","tag":"CookFish","hp":4,"eff":"DefenseUp","pot":2},
{"id":"Item_InsectGet_K","en":"Razorclaw Crab","ko":"칼날게","cat":"fish","tag":"CookFish","hp":4,"eff":"AttackUp","pot":2},
{"id":"Item_FishGet_M","en":"Sneaky River Snail","ko":"은밀우렁이","cat":"fish","tag":"CookFish","hp":4,"eff":"QuietnessUp","pot":1},
{"id":"Item_FishGet_G","en":"Armored Porgy","ko":"갑옷도미","cat":"fish","tag":"CookFish","hp":4,"eff":"DefenseUp","pot":3},
{"id":"Item_FishGet_F","en":"Mighty Porgy","ko":"칼날도미","cat":"fish","tag":"CookFish","hp":4,"eff":"AttackUp","pot":3},
{"id":"Item_FishGet_AC","en":"Glowing Cave Fish","ko":"조명동굴어","cat":"fish","tag":"CookFish","hp":4,"eff":"LightEmission","pot":2},
{"id":"Item_FishGet_AA","en":"Ancient Arowana","ko":"고대아로와나","cat":"fish","tag":"CookFish","hp":4},
{"id":"Item_FishGet_Z","en":"Sanke Carp","ko":"달록잉어","cat":"fish","tag":"CookFish","hp":4},
{"id":"Item_FishGet_H","en":"Armored Carp","ko":"갑옷잉어","cat":"fish","tag":"CookFish","hp":4,"eff":"DefenseUp","pot":2},
{"id":"Item_FishGet_E","en":"Mighty Carp","ko":"칼날잉어","cat":"fish","tag":"CookFish","hp":4,"eff":"AttackUp","pot":2},
{"id":"Item_FishGet_X","en":"Stealthfin Trout","ko":"은밀송어","cat":"fish","tag":"CookFish","hp":4,"eff":"QuietnessUp","pot":2},
{"id":"Item_FishGet_D","en":"Voltfin Trout","ko":"찌릿찌릿송어","cat":"fish","tag":"CookFish","hp":4,"eff":"ResistElectric","pot":3},
{"id":"Item_FishGet_J","en":"Sizzlefin Trout","ko":"따끈따끈송어","cat":"fish","tag":"CookFish","hp":4,"eff":"ResistCold","pot":3},
{"id":"Item_FishGet_C","en":"Chillfin Trout","ko":"썰렁송어","cat":"fish","tag":"CookFish","hp":4,"eff":"ResistHot","pot":3},
{"id":"Item_FishGet_L","en":"Staminoka Bass","ko":"원기배스","cat":"fish","tag":"CookFish","hp":4,"eff":"StaminaRecover","pot":4},
{"id":"Item_FishGet_A","en":"Hyrule Bass","ko":"하이랄배스","cat":"fish","tag":"CookFish","hp":4},
{"id":"Item_FishGet_B","en":"Hearty Bass","ko":"맥스배스","cat":"fish","tag":"CookFish","hp":8,"eff":"LifeMaxUp","pot":8},
{"id":"Item_FishGet_I","en":"Hearty Salmon","ko":"맥스연어","cat":"fish","tag":"CookFish","hp":16,"eff":"LifeMaxUp","pot":16},
{"id":"Item_Enemy_24","en":"Molduga Fin","ko":"몰드래고의 등지느러미","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_156","en":"Gleeok Wing","ko":"그리오크의 날개","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_123","en":"Gibdo Wing","ko":"기브도의 날개","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_124","en":"Aerocuda Wing","ko":"카쿠다의 날개","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_45","en":"Electric Keese Wing","ko":"일렉트로 키이스의 날개","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_46","en":"Ice Keese Wing","ko":"아이스 키이스의 날개","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_44","en":"Fire Keese Wing","ko":"파이어 키이스의 날개","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_18","en":"Keese Wing","ko":"키이스의 날개","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"Item_Enemy_66","en":"Aerocuda Eyeball","ko":"카쿠다의 눈알","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_21","en":"Octorok Eyeball","ko":"옥타의 눈알","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_118","en":"Electric Keese Eyeball","ko":"일렉트로 키이스의 눈알","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_119","en":"Ice Keese Eyeball","ko":"아이스 키이스의 눈알","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_117","en":"Fire Keese Eyeball","ko":"파이어 키이스의 눈알","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_Enemy_19","en":"Keese Eyeball","ko":"키이스의 눈알","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"Item_PlantGet_U","en":"Korok Frond","ko":"코로그 잎새","cat":"veg","tag":"CookPlant","hp":1},
{"id":"Item_Enemy_57","en":"Octo Balloon","ko":"옥타 풍선","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"LightFruit","en":"Dazzlefruit","ko":"광휘의 열매","cat":"fruit","tag":"CookFruit","hp":1,"pot":1},
{"id":"Item_Enemy_40","en":"Chuchu Jelly","ko":"츄츄젤리","cat":"monster","tag":"CookEnemy","sTime":40},
{"id":"WaterFruit","en":"Splash Fruit","ko":"물 열매","cat":"fruit","tag":"CookFruit","hp":1,"eff":"SwimSpeedUp","pot":1},
{"id":"Item_Enemy_16","en":"Yellow Chuchu Jelly","ko":"노란츄츄젤리","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"ElectricalFruit","en":"Shock Fruit","ko":"전기 열매","cat":"fruit","tag":"CookFruit","hp":1,"eff":"AttackUpThunderstorm","pot":1},
{"id":"Item_Enemy_17","en":"White Chuchu Jelly","ko":"하얀츄츄젤리","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"IceFruit","en":"Ice Fruit","ko":"냉기의 열매","cat":"fruit","tag":"CookFruit","hp":1,"eff":"AttackUpCold","pot":1},
{"id":"Item_Enemy_15","en":"Red Chuchu Jelly","ko":"빨간츄츄젤리","cat":"monster","tag":"CookEnemy","sTime":80,"crit":10},
{"id":"FireFruit","en":"Fire Fruit","ko":"화염의 열매","cat":"fruit","tag":"CookFruit","hp":1,"eff":"AttackUpHot","pot":1},
{"id":"LightBall_Large","en":"Giant Brightbloom Seed","ko":"거대한 조명꽃 씨앗","cat":"fruit","tag":"CookFruit"},
{"id":"LightBall_Small","en":"Brightbloom Seed","ko":"조명꽃 씨앗","cat":"fruit","tag":"CookFruit"},
{"id":"Item_KingScale","en":"King's Scale","ko":"왕의 비늘","cat":"mineral","tag":"CookOre"},
{"id":"Animal_Insect_B","en":"Tireless Frog","ko":"활력개구리","cat":"critter","tag":"CookInsect","hp":8,"eff":"ExStaminaMaxUp","pot":2},
{"id":"Animal_Insect_F","en":"Fairy","ko":"요정","cat":"special","tag":"CookOther","hp":20},
{"id":"Animal_Insect_M","en":"Hearty Lizard","ko":"맥스도마뱀","cat":"critter","tag":"CookInsect","hp":16,"eff":"LifeMaxUp","pot":16},
{"id":"BeeHome","en":"Courser Bee Honey","ko":"원기벌의 벌꿀","cat":"other","tag":"CookSpice","hp":8,"eff":"StaminaRecover","pot":2},
{"id":"FldObj_Pinecone_A_01","en":"Hylian Pine Cone","ko":"하이랄솔방울","cat":"mineral","tag":"CookOre"},
{"id":"Item_Enemy_02","en":"Bokoblin Guts","ko":"보코블린의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_05","en":"Lizalfos Tail","ko":"리잘포스의 꼬리","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_08","en":"Moblin Guts","ko":"모리블린의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_105","en":"Horriblin Guts","ko":"호러블린의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_114","en":"Blue Lizalfos Tail","ko":"블루 리잘포스의 꼬리","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_115","en":"Black Lizalfos Tail","ko":"블랙 리잘포스의 꼬리","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_116","en":"Silver Lizalfos Tail","ko":"실버 리잘포스의 꼬리","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_121","en":"Gibdo Guts","ko":"기브도의 간","cat":"monster","tag":"CookEnemy","sTime":80,"crit":100},
{"id":"Item_Enemy_136","en":"Boss Bokoblin Guts","ko":"보스보코블린의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_14","en":"Lynel Guts","ko":"라이넬의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_157","en":"Gleeok Guts","ko":"그리오크의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_190","en":"Frox Guts","ko":"데그가마의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_25","en":"Molduga Guts","ko":"몰드래고의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_34","en":"Hinox Guts","ko":"히녹스의 간","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_41","en":"Fire-Breath Lizalfos Tail","ko":"화염 리잘포스의 꼬리","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_42","en":"Ice-Breath Lizalfos Tail","ko":"얼음 리잘포스의 꼬리","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Enemy_43","en":"Electric Lizalfos Tail","ko":"마비 리잘포스의 꼬리","cat":"monster","tag":"CookEnemy","sTime":160,"crit":30},
{"id":"Item_Fruit_A","en":"Apple","ko":"사과","cat":"fruit","tag":"CookFruit","hp":2},
{"id":"Item_Fruit_B","en":"Wildberry","ko":"딸기","cat":"fruit","tag":"CookFruit","hp":2},
{"id":"Item_Fruit_C","en":"Voltfruit","ko":"찌릿찌릿프루트","cat":"fruit","tag":"CookFruit","hp":2,"eff":"ResistElectric","pot":1},
{"id":"Item_Fruit_E","en":"Fleet-Lotus Seeds","ko":"고고연꽃 열매","cat":"fruit","tag":"CookFruit","hp":2,"eff":"AllSpeed","pot":2},
{"id":"Item_Fruit_F","en":"Hydromelon","ko":"썰렁멜론","cat":"fruit","tag":"CookFruit","hp":2,"eff":"ResistHot","pot":1},
{"id":"Item_Fruit_G","en":"Palm Fruit","ko":"야자열매","cat":"fruit","tag":"CookFruit","hp":4},
{"id":"Item_Fruit_H","en":"Mighty Bananas","ko":"칼날바나나","cat":"fruit","tag":"CookFruit","hp":2,"eff":"AttackUp","pot":2},
{"id":"Item_Fruit_I","en":"Spicy Pepper","ko":"따끈따끈초 열매","cat":"fruit","tag":"CookFruit","hp":2,"eff":"ResistCold","pot":1},
{"id":"Item_Fruit_J","en":"Fortified Pumpkin","ko":"갑옷호박","cat":"veg","tag":"CookPlant","hp":2,"eff":"DefenseUp","pot":2},
{"id":"Item_Fruit_K","en":"Acorn","ko":"도토리","cat":"other","tag":"CookSpice","hp":1,"sHp":2,"sTime":20},
{"id":"Item_Fruit_L","en":"Chickaloo Tree Nut","ko":"작은 새 나무 열매","cat":"other","tag":"CookSpice","hp":1,"sHp":2,"sTime":10},
{"id":"Item_Fruit_M","en":"Hylian Tomato","ko":"하이랄토마토","cat":"fruit","tag":"CookFruit","hp":4},
{"id":"Item_Fruit_N","en":"Sun Pumpkin","ko":"해품이호박","cat":"veg","tag":"CookPlant","hp":2,"eff":"LifeRepair","pot":4},
{"id":"Item_Fruit_P","en":"Golden Apple","ko":"황금 사과","cat":"fruit","tag":"CookFruit","hp":6,"sTime":20,"crit":100},
{"id":"Item_Material_01","en":"Cane Sugar","ko":"사탕수수","cat":"other","tag":"CookSpice","sTime":50,"crit":30},
{"id":"Item_Material_02","en":"Goron Spice","ko":"고론의 향신료","cat":"other","tag":"CookSpice","pot":1,"sTime":60,"crit":10},
{"id":"Item_Material_03","en":"Hylian Rice","ko":"하이랄 쌀","cat":"other","tag":"CookSpice","hp":4,"sTime":30},
{"id":"Item_Material_04","en":"Bird Egg","ko":"새의 알","cat":"other","tag":"CookSpice","hp":4,"sTime":60,"crit":10},
{"id":"Item_Material_05","en":"Fresh Milk","ko":"신선 우유","cat":"other","tag":"CookSpice","hp":2,"sTime":50},
{"id":"Item_Material_06","en":"Goat Butter","ko":"염소 버터","cat":"other","tag":"CookSpice","sTime":50,"crit":10},
{"id":"Item_Material_07","en":"Tabantha Wheat","ko":"타반타 밀","cat":"other","tag":"CookSpice","hp":4,"sTime":30},
{"id":"Item_Material_08","en":"Monster Extract","ko":"몬스터엑기스","cat":"other","tag":"CookSpice"},
{"id":"Item_Material_09","en":"Oil Jar","ko":"기름병","cat":"other","tag":"CookSpice","sTime":50,"crit":10},
{"id":"Item_Material_10","en":"Hateno Cheese","ko":"하테노 치즈","cat":"other","tag":"CookSpice","hp":4,"sTime":50,"crit":10},
{"id":"Item_Material_11","en":"Dark Clump","ko":"어둠 덩어리","cat":"other","tag":"CookSpice","eff":"MiasmaGuard","pot":1},
{"id":"Item_Meat_01","en":"Raw Meat","ko":"짐승 고기","cat":"meat","tag":"CookMeat","hp":4},
{"id":"Item_Meat_02","en":"Raw Prime Meat","ko":"상급 짐승 고기","cat":"meat","tag":"CookMeat","hp":6},
{"id":"Item_Meat_06","en":"Raw Bird Drumstick","ko":"새 고기","cat":"meat","tag":"CookMeat","hp":4},
{"id":"Item_Meat_07","en":"Raw Bird Thigh","ko":"상급 새 고기","cat":"meat","tag":"CookMeat","hp":6},
{"id":"Item_Meat_11","en":"Raw Gourmet Meat","ko":"특급 짐승 고기","cat":"meat","tag":"CookMeat","hp":12},
{"id":"Item_Meat_12","en":"Raw Whole Bird","ko":"특급 새 고기","cat":"meat","tag":"CookMeat","hp":12},
{"id":"Item_MushroomGet_D","en":"Rushroom","ko":"고고버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"AllSpeed","pot":1},
{"id":"Item_MushroomGet_K","en":"Brightcap","ko":"조명버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"LightEmission","pot":1},
{"id":"Item_Mushroom_A","en":"Stamella Shroom","ko":"원기버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"StaminaRecover","pot":1},
{"id":"Item_Mushroom_B","en":"Chillshroom","ko":"썰렁버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"ResistHot","pot":2},
{"id":"Item_Mushroom_C","en":"Sunshroom","ko":"따끈따끈버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"ResistCold","pot":2},
{"id":"Item_Mushroom_E","en":"Hylian Shroom","ko":"하이랄버섯","cat":"mushroom","tag":"CookMushroom","hp":2},
{"id":"Item_Mushroom_F","en":"Hearty Truffle","ko":"맥스트러플","cat":"mushroom","tag":"CookMushroom","hp":8,"eff":"LifeMaxUp","pot":4},
{"id":"Item_Mushroom_H","en":"Zapshroom","ko":"찌릿찌릿버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"ResistElectric","pot":2},
{"id":"Item_Mushroom_J","en":"Silent Shroom","ko":"은밀버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"QuietnessUp","pot":2},
{"id":"Item_Mushroom_L","en":"Razorshroom","ko":"칼날버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"AttackUp","pot":2},
{"id":"Item_Mushroom_M","en":"Ironshroom","ko":"갑옷버섯","cat":"mushroom","tag":"CookMushroom","hp":2,"eff":"DefenseUp","pot":2},
{"id":"Item_Mushroom_N","en":"Big Hearty Truffle","ko":"큰맥스트러플","cat":"mushroom","tag":"CookMushroom","hp":12,"eff":"LifeMaxUp","pot":16},
{"id":"Item_Mushroom_O","en":"Endura Shroom","ko":"활력버섯","cat":"mushroom","tag":"CookMushroom","hp":4,"eff":"ExStaminaMaxUp","pot":1},
{"id":"Item_Mushroom_P","en":"Skyshroom","ko":"하늘버섯","cat":"mushroom","tag":"CookMushroom","hp":1},
{"id":"Item_Ore_A","en":"Diamond","ko":"다이아몬드","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_B","en":"Ruby","ko":"루비","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_C","en":"Sapphire","ko":"사파이어","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_D","en":"Topaz","ko":"토파즈","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_E","en":"Opal","ko":"오팔","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_F","en":"Amber","ko":"호박","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_G","en":"Luminous Stone","ko":"야광석","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_H","en":"Rock Salt","ko":"암염","cat":"other","tag":"CookSpice","sTime":30},
{"id":"Item_Ore_I","en":"Flint","ko":"부싯돌","cat":"mineral","tag":"CookOre"},
{"id":"Item_Ore_J","en":"Star Fragment","ko":"별의 조각","cat":"special","tag":"CookSpice","sTime":60,"crit":100},
{"id":"Item_PlantGet_A","en":"Hyrule Herb","ko":"하이랄초","cat":"veg","tag":"CookPlant","hp":4},
{"id":"Item_PlantGet_B","en":"Hearty Radish","ko":"맥스순무","cat":"veg","tag":"CookPlant","hp":10,"eff":"LifeMaxUp","pot":12},
{"id":"Item_PlantGet_C","en":"Big Hearty Radish","ko":"큰맥스순무","cat":"veg","tag":"CookPlant","hp":16,"eff":"LifeMaxUp","pot":20},
{"id":"Item_PlantGet_E","en":"Cool Safflina","ko":"썰렁허브","cat":"veg","tag":"CookPlant","eff":"ResistHot","pot":1},
{"id":"Item_PlantGet_F","en":"Warm Safflina","ko":"따끈따끈허브","cat":"veg","tag":"CookPlant","eff":"ResistCold","pot":1},
{"id":"Item_PlantGet_G","en":"Mighty Thistle","ko":"칼날초","cat":"veg","tag":"CookPlant","eff":"AttackUp","pot":1},
{"id":"Item_PlantGet_H","en":"Armoranth","ko":"갑옷초","cat":"veg","tag":"CookPlant","eff":"DefenseUp","pot":1},
{"id":"Item_PlantGet_I","en":"Blue Nightshade","ko":"은밀초","cat":"veg","tag":"CookPlant","eff":"QuietnessUp","pot":1},
{"id":"Item_PlantGet_J","en":"Silent Princess","ko":"고요한 공주","cat":"veg","tag":"CookPlant","hp":4,"eff":"QuietnessUp","pot":3},
{"id":"Item_PlantGet_L","en":"Electric Safflina","ko":"찌릿찌릿허브","cat":"veg","tag":"CookPlant","eff":"ResistElectric","pot":1},
{"id":"Item_PlantGet_M","en":"Swift Carrot","ko":"고고당근","cat":"veg","tag":"CookPlant","hp":2,"eff":"AllSpeed","pot":1},
{"id":"Item_PlantGet_O","en":"Swift Violet","ko":"고고제비꽃","cat":"veg","tag":"CookPlant","eff":"AllSpeed","pot":2},
{"id":"Item_PlantGet_Q","en":"Endura Carrot","ko":"활력당근","cat":"veg","tag":"CookPlant","hp":8,"eff":"ExStaminaMaxUp","pot":4},
{"id":"Item_PlantGet_R","en":"Sundelion","ko":"해품이꽃","cat":"veg","tag":"CookPlant","eff":"LifeRepair","pot":12},
{"id":"Item_PlantGet_S","en":"Stambulb","ko":"원기초","cat":"veg","tag":"CookPlant","hp":2,"eff":"StaminaRecover","pot":1},
{"id":"Obj_FireWoodBundle","en":"Wood","ko":"장작 묶음","cat":"mineral","tag":"CookOre"}],"recipes":[{"en":"Fairy Tonic","ko":"요정의 활력수","img":"Fairy Tonic","parts":[["Animal_Insect_F"],["CookGolem","CookForeign"]],"kind":"fairy","bonusHp":-12,"book":228},
{"en":"Fairy Tonic","ko":"요정의 활력수","img":"Fairy Tonic","parts":[["Animal_Insect_F"],["CookOre"],["CookInsect"],["CookEnemy"]],"kind":"fairy","bonusHp":-12,"book":228},
{"en":"Fairy Tonic","ko":"요정의 활력수","img":"Fairy Tonic","parts":[["Animal_Insect_F"],["CookInsect"],["CookEnemy"]],"kind":"fairy","bonusHp":-12,"book":228},
{"en":"Fairy Tonic","ko":"요정의 활력수","img":"Fairy Tonic","parts":[["Animal_Insect_F"],["CookOre","CookEnemy","CookInsect"]],"kind":"fairy","bonusHp":-12,"book":228},
{"en":"Dubious Food","ko":"애매한 요리","img":"Dubious Food","parts":[["CookForeign"]],"kind":"dubious","book":145},
{"en":"Dubious Food","ko":"애매한 요리","img":"Dubious Food","parts":[["CookGolem"]],"kind":"dubious","book":145},
{"en":"Rock-Hard Food","ko":"너무 딱딱한 요리","img":"Rock-Hard Food","parts":[["CookOre"]],"kind":"rockhard","book":146},
{"en":"Elixir","ko":"물약","img":"Elixir","parts":[["CookEnemy"],["CookInsect"]],"kind":"elixir","book":229},
{"en":"Dubious Food","ko":"애매한 요리","img":"Dubious Food","parts":[["CookEnemy","CookInsect"]],"kind":"dubious","book":145},
{"en":"Fruitcake","ko":"프루트케이크","img":"Fruitcake","parts":[["Item_Fruit_A","Item_Fruit_B","Item_Fruit_P"],["Item_Fruit_B","Item_Fruit_C","Item_Fruit_F","Item_Fruit_H","Item_Fruit_G","Item_Fruit_A","Item_Fruit_P"],["Item_Material_07"],["Item_Material_01"]],"bonusHp":4,"book":126},
{"en":"Seafood Paella","ko":"해물 파에야","img":"Seafood Paella","parts":[["Item_FishGet_F","Item_FishGet_G"],["Item_InsectGet_K","Item_InsectGet_O"],["Item_Material_03"],["Item_Material_06"],["Item_Ore_H"]],"book":88},
{"en":"Dark Stew","ko":"마인전골","img":"Dark Stew","parts":[["Item_Material_11"],["CookMeat"],["CookFish"]],"book":140},
{"en":"Dark Rice Ball","ko":"마인 주먹밥","img":"Dark Rice Ball","parts":[["Item_Material_11"],["Item_Ore_H"],["Item_Material_03"]],"book":143},
{"en":"Dark Soup","ko":"마인수프","img":"Dark Soup","parts":[["Item_Material_11"],["Item_Material_07"],["Item_Material_06"],["Item_Material_05"]],"book":141},
{"en":"Dark Curry","ko":"마인 카레","img":"Dark Curry","parts":[["Item_Material_11"],["Item_Material_02"],["Item_Material_03"]],"book":142},
{"en":"Dark Cake","ko":"마인 케이크","img":"Dark Cake","parts":[["Item_Material_11"],["Item_Material_01"],["Item_Material_07"],["Item_Material_06"]],"book":144},
{"en":"Monster Curry","ko":"몬스터 카레","img":"Monster Curry","parts":[["Item_Material_03"],["Item_Material_02"],["Item_Material_08"]],"book":137},
{"en":"Monster Rice Balls","ko":"몬스터 주먹밥","img":"Monster Rice Balls","parts":[["Item_Material_03"],["Item_Ore_H"],["Item_Material_08"]],"book":138},
{"en":"Monster Cake","ko":"몬스터 케이크","img":"Monster Cake","parts":[["Item_Material_07"],["Item_Material_01"],["Item_Material_08"],["Item_Material_06"]],"book":139},
{"en":"Monster Soup","ko":"몬스터수프","img":"Monster Soup","parts":[["Item_Material_07"],["Item_Material_06"],["Item_Material_05"],["Item_Material_08"]],"book":136},
{"en":"Monster Stew","ko":"몬스터전골","img":"Monster Stew","parts":[["CookMeat"],["CookFish"],["Item_Material_08"]],"book":135},
{"en":"Creamy Heart Soup","ko":"하트 밀크수프","img":"Creamy Heart Soup","parts":[["Item_PlantGet_B","Item_PlantGet_C"],["Item_Fruit_C"],["Item_Fruit_F"],["Item_Material_05"]],"book":59},
{"en":"Snail Chowder","ko":"조개 차우더","img":"Snail Chowder","parts":[["Item_FishGet_M"],["Item_Material_07"],["Item_Material_05"],["Item_Material_06"]],"book":58},
{"en":"Pumpkin Stew","ko":"호박 스튜","img":"Pumpkin Stew","parts":[["Item_Fruit_J","Item_Fruit_N"],["Item_Material_07"],["Item_Material_05"],["Item_Material_06"]],"book":75},
{"en":"Gourmet Meat Stew","ko":"특급 고기 스튜","img":"Gourmet Meat Stew","parts":[["Item_Meat_11","Item_Meat_12"],["Item_Material_07"],["Item_Material_05"],["Item_Material_06"]],"book":78},
{"en":"Prime Meat Stew","ko":"상급 고기 스튜","img":"Prime Meat Stew","parts":[["Item_Meat_02","Item_Meat_07"],["Item_Material_07"],["Item_Material_05"],["Item_Material_06"]],"book":77},
{"en":"Meat Stew","ko":"고기 스튜","img":"Meat Stew","parts":[["Item_Meat_01","Item_Meat_06"],["Item_Material_07"],["Item_Material_05"],["Item_Material_06"]],"book":76},
{"en":"Gourmet Meat Curry","ko":"특급 고기 카레","img":"Gourmet Meat Curry","parts":[["Item_Meat_11"],["Item_Material_03"],["Item_Material_02"]],"book":68},
{"en":"Gourmet Poultry Curry","ko":"특급 치킨 카레","img":"Gourmet Poultry Curry","parts":[["Item_Meat_12"],["Item_Material_03"],["Item_Material_02"]],"book":71},
{"en":"Prime Meat Curry","ko":"상급 고기 카레","img":"Prime Meat Curry","parts":[["Item_Meat_02"],["Item_Material_03"],["Item_Material_02"]],"book":67},
{"en":"Prime Poultry Curry","ko":"상급 치킨 카레","img":"Prime Poultry Curry","parts":[["Item_Meat_07"],["Item_Material_03"],["Item_Material_02"]],"book":70},
{"en":"Meat Curry","ko":"짐승 고기 카레","img":"Meat Curry","parts":[["Item_Meat_01"],["Item_Material_03"],["Item_Material_02"]],"book":66},
{"en":"Poultry Curry","ko":"치킨 카레","img":"Poultry Curry","parts":[["Item_Meat_06"],["Item_Material_03"],["Item_Material_02"]],"book":69},
{"en":"Seafood Curry","ko":"해산물 카레","img":"Seafood Curry","parts":[["Item_FishGet_F","Item_FishGet_G"],["Item_Material_03"],["Item_Material_02"]],"book":72},
{"en":"Vegetable Curry","ko":"야채 카레","img":"Vegetable Curry","parts":[["Item_Fruit_J","Item_PlantGet_M","Item_PlantGet_Q","Item_Fruit_N"],["Item_Material_03"],["Item_Material_02"]],"book":65},
{"en":"Pumpkin Pie","ko":"호박 케이크","img":"Pumpkin Pie","parts":[["Item_Fruit_J","Item_Fruit_N"],["Item_Material_07"],["Item_Material_01"],["Item_Material_06"]],"book":128},
{"en":"Carrot Cake","ko":"당근 케이크","img":"Carrot Cake","parts":[["Item_PlantGet_M","Item_PlantGet_Q"],["Item_Material_07"],["Item_Material_01"],["Item_Material_06"]],"book":127},
{"en":"Wildberry Crepe","ko":"딸기 크레이프","img":"Wildberry Crepe","parts":[["Item_Material_07"],["Item_Material_05"],["Item_Material_04"],["Item_Material_01"],["Item_Fruit_B"]],"bonusHp":16,"book":123},
{"en":"Honey Crepe","ko":"벌꿀 크레이프","img":"Honey Crepe","parts":[["Item_Material_07"],["Item_Material_05"],["Item_Material_04"],["Item_Material_01"],["BeeHome"]],"bonusHp":4,"book":124},
{"en":"Plain Crepe","ko":"플레인 크레이프","img":"Plain Crepe","parts":[["Item_Material_07"],["Item_Material_05"],["Item_Material_04"],["Item_Material_01"]],"book":122},
{"en":"Apple Pie","ko":"애플파이","img":"Apple Pie","parts":[["Item_Fruit_A","Item_Fruit_P"],["Item_Material_07"],["Item_Material_06"],["Item_Material_01"]],"book":131},
{"en":"Nutcake","ko":"너츠 케이크","img":"Nutcake","parts":[["Item_Material_07"],["Item_Material_06"],["Item_Material_01"],["Item_Fruit_L","Item_Fruit_K"]],"book":125},
{"en":"Egg Tart","ko":"에그 타르트","img":"Egg Tart","parts":[["Item_Material_04"],["Item_Material_07"],["Item_Material_06"],["Item_Material_01"]],"book":132},
{"en":"Egg Pudding","ko":"달걀 푸딩","img":"Egg Pudding","parts":[["Item_Material_04"],["Item_Material_05"],["Item_Material_01"]],"book":121},
{"en":"Fried Bananas","ko":"튀긴 바나나","img":"Fried Bananas","parts":[["Item_Fruit_H"],["Item_Material_07"],["Item_Material_01"]],"book":120},
{"en":"Fruit Pie","ko":"프루트 파이","img":"Fruit Pie","parts":[["CookFruit"],["Item_Material_07"],["Item_Material_06"],["Item_Material_01"]],"book":130},
{"en":"Meat Pie","ko":"미트 파이","img":"Meat Pie","parts":[["CookMeat"],["Item_Material_07"],["Item_Material_06"],["Item_Ore_H"]],"book":108},
{"en":"Fish Pie","ko":"피시 파이","img":"Fish Pie","parts":[["CookFish"],["Item_Material_07"],["Item_Material_06"],["Item_Ore_H"]],"book":109},
{"en":"Salmon Meunière","ko":"연어 뫼니에르","img":"Salmon Meunière","parts":[["Item_FishGet_I"],["Item_Material_06"],["Item_Material_07"]],"book":45},
{"en":"Salmon Risotto","ko":"연어 리조또","img":"Salmon Risotto","parts":[["Item_FishGet_I"],["Item_Material_03"],["Item_Ore_H"],["Item_Material_06"]],"book":82},
{"en":"Crab Risotto","ko":"게살 리조또","img":"Crab Risotto","parts":[["Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"],["Item_Material_03"],["Item_Ore_H"],["Item_Material_06"]],"book":83},
{"en":"Vegetable Risotto","ko":"야채 리조또","img":"Vegetable Risotto","parts":[["Item_Fruit_J","Item_PlantGet_M","Item_PlantGet_Q","Item_Fruit_N"],["Item_Material_03"],["Item_Ore_H"],["Item_Material_06"]],"book":80},
{"en":"Mushroom Risotto","ko":"버섯 리조또","img":"Mushroom Risotto","parts":[["CookMushroom"],["Item_Material_03"],["Item_Ore_H"],["Item_Material_06"]],"book":81},
{"en":"Cream of Mushroom Soup","ko":"버섯 밀크수프","img":"Cream of Mushroom Soup","parts":[["CookMushroom"],["CookPlant"],["Item_Ore_H"],["Item_Material_05"]],"book":55},
{"en":"Veggie Cream Soup","ko":"야채 크림수프","img":"Veggie Cream Soup","parts":[["Item_Fruit_J","Item_PlantGet_M","Item_PlantGet_Q","Item_Fruit_N"],["Item_Ore_H"],["Item_Material_05"]],"book":54},
{"en":"Creamy Meat Soup","ko":"고기 밀크수프","img":"Creamy Meat Soup","parts":[["CookMeat"],["CookPlant"],["Item_Ore_H"],["Item_Material_05"]],"book":56},
{"en":"Creamy Seafood Soup","ko":"생선 밀크수프","img":"Creamy Seafood Soup","parts":[["CookFish"],["CookPlant"],["Item_Ore_H"],["Item_Material_05"]],"book":57},
{"en":"Cream of Vegetable Soup","ko":"야채 밀크수프","img":"Cream of Vegetable Soup","parts":[["CookPlant"],["Item_Ore_H"],["Item_Material_05"]],"book":53},
{"en":"Veggie Porridge","ko":"야채 우유 죽","img":"Veggie Porridge","parts":[["CookPlant"],["Item_Material_03"],["Item_Material_05"]],"book":104},
{"en":"Fruity Tomato Stew","ko":"토마토수프","img":"Fruity Tomato Stew","parts":[["Item_Fruit_M"],["Item_Material_05"],["Item_Ore_H"]],"book":50},
{"en":"Steamed Tomatoes","ko":"야채 토마토찜","img":"Steamed Tomatoes","parts":[["CookPlant"],["Item_Fruit_M"]],"book":10},
{"en":"Tomato Mushroom Stew","ko":"버섯 토마토전골","img":"Tomato Mushroom Stew","parts":[["CookMushroom"],["Item_Fruit_M"]],"book":51},
{"en":"Tomato Seafood Soup","ko":"해산물 토마토수프","img":"Tomato Seafood Soup","parts":[["CookFish"],["Item_Fruit_M"]],"book":52},
{"en":"Crunchy Fried Rice","ko":"고슬고슬 볶음밥","img":"Crunchy Fried Rice","parts":[["CookMeat"],["Item_Material_09"],["Item_Material_03"],["Item_Material_04"]],"book":91},
{"en":"Cheesecake","ko":"치즈 케이크","img":"Cheesecake","parts":[["Item_Material_10"],["Item_Material_07"],["Item_Material_01"]],"book":129},
{"en":"Cheesy Risotto","ko":"치즈 리조또","img":"Cheesy Risotto","parts":[["CookFish","CookMushroom","CookPlant"],["Item_Material_10"],["Item_Material_03"],["Item_Ore_H"]],"book":84},
{"en":"Cheesy Omelet","ko":"치즈 오믈렛","img":"Cheesy Omelet","parts":[["CookMushroom","CookPlant"],["Item_Material_10"],["Item_Material_04"],["Item_Ore_H"]],"book":115},
{"en":"Noble Pursuit","ko":"브아이 밋 브오이","img":"Noble Pursuit","parts":[["Item_Fruit_G"],["Item_Fruit_F"],["Item_Fruit_C"],["Item_Ore_H"]],"book":134},
{"en":"Hylian Tomato Pizza","ko":"토마토 피자","img":"Hylian Tomato Pizza","parts":[["Item_Fruit_M"],["Item_Material_07"],["Item_Material_10"]],"book":107},
{"en":"Fragrant Seafood Stew","ko":"오일 해산물전골","img":"Fragrant Seafood Stew","parts":[["CookFish"],["Item_PlantGet_S"],["Item_Material_09"]],"book":39},
{"en":"Deep-Fried Drumstick","ko":"오일 새 고기 튀김","img":"Deep-Fried Drumstick","parts":[["Item_Meat_06"],["Item_Material_09"]],"book":40},
{"en":"Deep-Fried Thigh","ko":"오일 상급 새 고기 튀김","img":"Deep-Fried Thigh","parts":[["Item_Meat_07"],["Item_Material_09"]],"book":41},
{"en":"Deep-Fried Bird Roast","ko":"오일 특급 새 고기 튀김","img":"Deep-Fried Bird Roast","parts":[["Item_Meat_12"],["Item_Material_09"]],"book":42},
{"en":"Melty Cheesy Bread","ko":"사르르 치즈 빵","img":"Melty Cheesy Bread","parts":[["Item_Material_07"],["Item_Material_10"]],"book":106},
{"en":"Cheesy Baked Fish","ko":"해산물과 치즈구이","img":"Cheesy Baked Fish","parts":[["CookFish"],["Item_Material_10"]],"book":111},
{"en":"Cheesy Curry","ko":"치즈 카레","img":"Cheesy Curry","parts":[["Item_Material_03"],["Item_Material_10"],["Item_Material_02"]],"book":73},
{"en":"Cheesy Meat Bowl","ko":"치즈 짐승 고기덮밥","img":"Cheesy Meat Bowl","parts":[["Item_Meat_01"],["Item_Material_03"],["Item_Material_10"],["Item_Ore_H"]],"book":97},
{"en":"Prime Cheesy Meat Bowl","ko":"상급 치즈 짐승 고기덮밥","img":"Prime Cheesy Meat Bowl","parts":[["Item_Meat_02"],["Item_Material_03"],["Item_Material_10"],["Item_Ore_H"]],"book":98},
{"en":"Gourmet Cheesy Meat Bowl","ko":"특급 치즈 짐승 고기덮밥","img":"Gourmet Cheesy Meat Bowl","parts":[["Item_Meat_11"],["Item_Material_03"],["Item_Material_10"],["Item_Ore_H"]],"book":99},
{"en":"Cheesy Tomato","ko":"치즈 토마토","img":"Cheesy Tomato","parts":[["Item_Fruit_M"],["Item_Material_10"]],"book":110},
{"en":"Carrot Stew","ko":"당근 스튜","img":"Carrot Stew","parts":[["Item_PlantGet_M","Item_PlantGet_Q"],["Item_Material_06"],["Item_Material_05"],["Item_Material_07"]],"book":74},
{"en":"Mushroom Omelet","ko":"버섯 오믈렛","img":"Mushroom Omelet","parts":[["CookMushroom"],["Item_Material_04"],["Item_Ore_H"],["Item_Material_06"]],"book":114},
{"en":"Crab Omelet with Rice","ko":"게살 달걀볶음밥","img":"Crab Omelet with Rice","parts":[["Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"],["Item_Material_04"],["Item_Material_03"],["Item_Ore_H"]],"book":93},
{"en":"Gourmet Poultry Pilaf","ko":"특급 치킨 필래프","img":"Gourmet Poultry Pilaf","parts":[["Item_Meat_12"],["Item_Material_04"],["Item_Material_03"],["Item_Material_06"]],"book":87},
{"en":"Prime Poultry Pilaf","ko":"상급 치킨 필래프","img":"Prime Poultry Pilaf","parts":[["Item_Meat_07"],["Item_Material_04"],["Item_Material_03"],["Item_Material_06"]],"book":86},
{"en":"Poultry Pilaf","ko":"치킨 필래프","img":"Poultry Pilaf","parts":[["Item_Meat_06"],["Item_Material_04"],["Item_Material_03"],["Item_Material_06"]],"book":85},
{"en":"Vegetable Omelet","ko":"야채 오믈렛","img":"Vegetable Omelet","parts":[["CookPlant"],["Item_Material_04"],["Item_Material_06"],["Item_Ore_H"]],"book":113},
{"en":"Porgy Meunière","ko":"도미 뫼니에르","img":"Porgy Meunière","parts":[["Item_FishGet_F","Item_FishGet_G"],["Item_Material_06"],["Item_Material_07"]],"book":44},
{"en":"Seafood Meunière","ko":"생선 뫼니에르","img":"Seafood Meunière","parts":[["CookFish"],["Item_Material_06"],["Item_Material_07"]],"book":43},
{"en":"Seafood Fried Rice","ko":"해물볶음밥","img":"Seafood Fried Rice","parts":[["Item_FishGet_F","Item_FishGet_G"],["Item_Material_03"],["Item_Ore_H"]],"book":92},
{"en":"Curry Pilaf","ko":"카레 필래프","img":"Curry Pilaf","parts":[["Item_Material_02"],["Item_Material_03"],["Item_Material_06"]],"book":89},
{"en":"Gourmet Meat and Rice Bowl","ko":"특급 짐승 고기덮밥","img":"Gourmet Meat and Rice Bowl","parts":[["Item_Meat_11"],["Item_Material_03"],["Item_Ore_H"]],"book":96},
{"en":"Prime Meat and Rice Bowl","ko":"상급 짐승 고기덮밥","img":"Prime Meat and Rice Bowl","parts":[["Item_Meat_02"],["Item_Material_03"],["Item_Ore_H"]],"book":95},
{"en":"Meat and Rice Bowl","ko":"짐승 고기덮밥","img":"Meat and Rice Bowl","parts":[["Item_Meat_01"],["Item_Material_03"],["Item_Ore_H"]],"book":94},
{"en":"Fried Egg and Rice","ko":"달걀프라이라이스","img":"Fried Egg and Rice","parts":[["Item_Material_03"],["Item_Material_04"]],"book":90},
{"en":"Meaty Rice Balls","ko":"고기 주먹밥","img":"Meaty Rice Balls","parts":[["CookMeat"],["Item_Material_03"]],"book":102},
{"en":"Seafood Rice Balls","ko":"해물 주먹밥","img":"Seafood Rice Balls","parts":[["CookFish"],["Item_Material_03"]],"book":103},
{"en":"Mushroom Rice Balls","ko":"버섯 주먹밥","img":"Mushroom Rice Balls","parts":[["CookMushroom"],["Item_Material_03"]],"book":101},
{"en":"Veggie Rice Balls","ko":"야채 주먹밥","img":"Veggie Rice Balls","parts":[["CookPlant"],["Item_Material_03"]],"book":100},
{"en":"Hot Buttered Apple","ko":"버터 바른 사과","img":"Hot Buttered Apple","parts":[["Item_Fruit_A","Item_Fruit_P"],["Item_Material_06"]],"bonusHp":4,"book":116},
{"en":"Meat-Stuffed Pumpkin","ko":"고기를 넣은 호박","img":"Meat-Stuffed Pumpkin","parts":[["Item_Fruit_J","Item_Fruit_N"],["CookMeat"]],"book":79},
{"en":"Glazed Meat","ko":"달게 조린 고기","img":"Glazed Meat","parts":[["CookMeat"],["BeeHome"]],"book":62},
{"en":"Glazed Seafood","ko":"달게 조린 생선","img":"Glazed Seafood","parts":[["CookFish"],["BeeHome"]],"book":63},
{"en":"Glazed Mushrooms","ko":"달게 조린 버섯","img":"Glazed Mushrooms","parts":[["CookMushroom"],["BeeHome"]],"book":61},
{"en":"Glazed Veggies","ko":"달게 조린 야채","img":"Glazed Veggies","parts":[["CookPlant"],["BeeHome"]],"book":60},
{"en":"Curry Rice","ko":"카레라이스","img":"Curry Rice","parts":[["Item_Material_03"],["Item_Material_02"]],"book":64},
{"en":"Honeyed Apple","ko":"꿀에 절인 사과","img":"Honeyed Apple","parts":[["Item_Fruit_A","Item_Fruit_P"],["BeeHome"]],"book":118},
{"en":"Honeyed Fruits","ko":"꿀에 절인 과일","img":"Honeyed Fruits","parts":[["CookFruit"],["BeeHome"]],"book":117},
{"en":"Gourmet Spiced Meat Skewer","ko":"특급 짐승 스테이크","img":"Gourmet Spiced Meat Skewer","parts":[["Item_Meat_11"],["Item_Material_02"]],"book":23},
{"en":"Prime Spiced Meat Skewer","ko":"상급 짐승 스테이크","img":"Prime Spiced Meat Skewer","parts":[["Item_Meat_02"],["Item_Material_02"]],"book":22},
{"en":"Spiced Meat Skewer","ko":"짐승 스테이크","img":"Spiced Meat Skewer","parts":[["Item_Meat_01"],["Item_Material_02"]],"book":21},
{"en":"Fragrant Mushroom Sauté","ko":"향긋한 버섯볶음","img":"Fragrant Mushroom Sauté","parts":[["CookMushroom"],["Item_Material_02"]],"book":36},
{"en":"Herb Sauté","ko":"향긋한 나물볶음","img":"Herb Sauté","parts":[["CookPlant"],["Item_Material_02"]],"book":35},
{"en":"Salt-Grilled Gourmet Meat","ko":"특급 고기 소금구이","img":"Salt-Grilled Gourmet Meat","parts":[["Item_Meat_11","Item_Meat_12"],["Item_Ore_H"]],"book":32},
{"en":"Salt-Grilled Prime Meat","ko":"상급 고기 소금구이","img":"Salt-Grilled Prime Meat","parts":[["Item_Meat_07","Item_Meat_02"],["Item_Ore_H"]],"book":31},
{"en":"Salt-Grilled Meat","ko":"고기 소금구이","img":"Salt-Grilled Meat","parts":[["Item_Meat_01","Item_Meat_06"],["Item_Ore_H"]],"book":30},
{"en":"Crab Stir-Fry","ko":"게볶음","img":"Crab Stir-Fry","parts":[["Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"],["Item_Material_02"]],"book":24},
{"en":"Salt-Grilled Crab","ko":"게 소금구이","img":"Salt-Grilled Crab","parts":[["Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"],["Item_Ore_H"]],"book":34},
{"en":"Fruity Tomato Stew","ko":"토마토수프","img":"Fruity Tomato Stew","parts":[["Item_Fruit_M"],["Item_Material_05"],["Item_Ore_H"]],"book":50},
{"en":"Salt-Grilled Fish","ko":"생선 소금구이","img":"Salt-Grilled Fish","parts":[["CookFish"],["Item_Ore_H"]],"book":33},
{"en":"Wheat Bread","ko":"밀 빵","img":"Wheat Bread","parts":[["Item_Material_07"],["Item_Ore_H"]],"book":105},
{"en":"Salt-Grilled Greens","ko":"야채 소금구이","img":"Salt-Grilled Greens","parts":[["CookPlant"],["Item_Ore_H"]],"book":28},
{"en":"Salt-Grilled Mushrooms","ko":"버섯 소금구이","img":"Salt-Grilled Mushrooms","parts":[["CookMushroom"],["Item_Ore_H"]],"book":29},
{"en":"Copious Meat Skewers","ko":"고기 꼬치구이 곱빼기","img":"Copious Meat Skewers","parts":[["CookMeat"],["CookMeat"],["CookMeat"],["CookMeat"]],"book":7},
{"en":"Copious Fried Wild Greens","ko":"야채구이 곱빼기","img":"Copious Fried Wild Greens","parts":[["CookPlant"],["CookPlant"],["CookPlant"],["CookPlant"]],"book":17},
{"en":"Copious Simmered Fruit","ko":"과일전골 곱빼기","img":"Copious Simmered Fruit","parts":[["CookFruit"],["CookFruit"],["CookFruit"],["CookFruit"]],"book":48},
{"en":"Copious Mushroom Skewers","ko":"버섯구이 곱빼기","img":"Copious Mushroom Skewers","parts":[["CookMushroom"],["CookMushroom"],["CookMushroom"],["CookMushroom"]],"book":20},
{"en":"Copious Seafood Skewers","ko":"생선 꼬치구이 곱빼기","img":"Copious Seafood Skewers","parts":[["CookFish"],["CookFish"],["CookFish"],["CookFish"]],"book":8},
{"en":"Meat Skewer","ko":"고기 꼬치구이","img":"Meat Skewer","parts":[["CookMeat"],["CookMeat"]],"book":4},
{"en":"Simmered Fruit","ko":"과일전골","img":"Simmered Fruit","parts":[["CookFruit"],["CookFruit"]],"book":47},
{"en":"Mushroom Skewer","ko":"버섯 꼬치구이","img":"Mushroom Skewer","parts":[["CookMushroom"],["CookMushroom"]],"book":1},
{"en":"Fried Wild Greens","ko":"야채구이","img":"Fried Wild Greens","parts":[["CookPlant"],["CookPlant"]],"book":16},
{"en":"Gourmet Meat and Seafood Fry","ko":"특급 고기와 생선구이","img":"Gourmet Meat and Seafood Fry","parts":[["Item_Meat_11","Item_Meat_12"],["CookFish"]],"book":27},
{"en":"Prime Meat and Seafood Fry","ko":"상급 고기와 생선구이","img":"Prime Meat and Seafood Fry","parts":[["Item_Meat_02","Item_Meat_07"],["CookFish"]],"book":26},
{"en":"Meat and Seafood Fry","ko":"고기와 생선구이","img":"Meat and Seafood Fry","parts":[["CookMeat"],["CookFish"]],"book":25},
{"en":"Pepper Steak","ko":"스파이시 고기구이","img":"Pepper Steak","parts":[["CookMeat"],["Item_Fruit_I"]],"book":37},
{"en":"Pepper Seafood","ko":"스파이시 생선구이","img":"Pepper Seafood","parts":[["CookFish"],["Item_Fruit_I"]],"book":38},
{"en":"Seafood Skewer","ko":"해산물 꼬치구이","img":"Seafood Skewer","parts":[["Item_FishGet_M","Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"],["CookFish"]],"book":6},
{"en":"Fish Skewer","ko":"생선 꼬치구이","img":"Fish Skewer","parts":[["CookFish"],["CookFish"]],"book":5},
{"en":"Steamed Meat","ko":"고기쌈구이","img":"Steamed Meat","parts":[["CookPlant"],["CookMeat"]],"book":12},
{"en":"Steamed Fish","ko":"생선쌈구이","img":"Steamed Fish","parts":[["CookPlant"],["CookFish"]],"book":13},
{"en":"Steamed Mushrooms","ko":"버섯쌈구이","img":"Steamed Mushrooms","parts":[["CookPlant"],["CookMushroom"]],"book":11},
{"en":"Steamed Fruit","ko":"과일찜","img":"Steamed Fruit","parts":[["CookPlant"],["CookFruit"]],"book":9},
{"en":"Fish and Mushroom Skewer","ko":"생선 꼬치구이와 버섯","img":"Fish and Mushroom Skewer","parts":[["CookMushroom"],["CookFish"]],"book":3},
{"en":"Meat and Mushroom Skewer","ko":"고기 꼬치구이와 버섯","img":"Meat and Mushroom Skewer","parts":[["CookMushroom"],["CookMeat"]],"book":2},
{"en":"Fruit and Mushroom Mix","ko":"과일 버섯무침","img":"Fruit and Mushroom Mix","parts":[["CookMushroom"],["CookFruit"]],"book":46},
{"en":"Fried Wild Greens","ko":"야채구이","img":"Fried Wild Greens","parts":[["Item_PlantGet_S"],["Item_Material_06"],["Item_Material_11"]],"book":16},
{"en":"Buttered Stambulb","ko":"버터볶음","img":"Buttered Stambulb","parts":[["Item_PlantGet_S"],["Item_Material_06"]],"book":19},
{"en":"Meat Skewer","ko":"고기 꼬치구이","img":"Meat Skewer","parts":[["CookMeat"]],"book":4},
{"en":"Seafood Skewer","ko":"해산물 꼬치구이","img":"Seafood Skewer","parts":[["Item_FishGet_M","Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"]],"book":6},
{"en":"Fish Skewer","ko":"생선 꼬치구이","img":"Fish Skewer","parts":[["CookFish"]],"book":5},
{"en":"Omelet","ko":"오믈렛","img":"Omelet","parts":[["Item_Material_04"]],"book":112},
{"en":"Milk","ko":"핫밀크","img":"Warm Milk","parts":[["Item_Material_05"]],"book":133},
{"en":"Mushroom Skewer","ko":"버섯 꼬치구이","img":"Mushroom Skewer","parts":[["CookMushroom"]],"book":1},
{"en":"Fried Wild Greens","ko":"야채구이","img":"Fried Wild Greens","parts":[["CookPlant"]],"book":16},
{"en":"Simmered Fruit","ko":"과일전골","img":"Simmered Fruit","parts":[["CookFruit"]],"book":47},
{"en":"Sautéed Nuts","ko":"너츠볶음","img":"Sautéed Nuts","parts":[["Item_Fruit_K"],["Item_Fruit_L"]],"book":15},
{"en":"Fairy Tonic","ko":"요정의 활력수","img":"Fairy Tonic","parts":[["Animal_Insect_F"]],"kind":"fairy","bonusHp":-12,"book":228}],"singles":[{"en":"Fairy Tonic","ko":"요정의 활력수","img":"Fairy Tonic","parts":[["Animal_Insect_F"]],"single":true,"kind":"fairy","bonusHp":-12,"book":228},
{"en":"Rock-Hard Food","ko":"너무 딱딱한 요리","img":"Rock-Hard Food","parts":[["CookOre"]],"single":true,"kind":"rockhard","book":146},
{"en":"Sautéed Peppers","ko":"따끈따끈볶음","img":"Sautéed Peppers","parts":[["Item_Fruit_I"]],"single":true,"book":14},
{"en":"Omelet","ko":"오믈렛","img":"Omelet","parts":[["Item_Material_04"]],"single":true,"book":112},
{"en":"Meat Skewer","ko":"고기 꼬치구이","img":"Meat Skewer","parts":[["CookMeat"]],"single":true,"book":4},
{"en":"Seafood Skewer","ko":"해산물 꼬치구이","img":"Seafood Skewer","parts":[["Item_FishGet_M","Item_InsectGet_K","Item_InsectGet_O","Item_InsectGet_Z"]],"single":true,"book":6},
{"en":"Fish Skewer","ko":"생선 꼬치구이","img":"Fish Skewer","parts":[["CookFish"]],"single":true,"book":5},
{"en":"Mushroom Skewer","ko":"버섯 꼬치구이","img":"Mushroom Skewer","parts":[["CookMushroom"]],"single":true,"book":1},
{"en":"Honey Candy","ko":"벌꿀 사탕","img":"Honey Candy","parts":[["BeeHome"]],"single":true,"bonusHp":-8,"book":119},
{"en":"Sautéed Nuts","ko":"너츠볶음","img":"Sautéed Nuts","parts":[["Item_Fruit_K","Item_Fruit_L"]],"single":true,"bonusHp":-2,"book":15},
{"en":"Milk","ko":"핫밀크","img":"Warm Milk","parts":[["Item_Material_05"]],"single":true,"bonusHp":2,"book":133},
{"en":"Cooked Stambulb","ko":"통구이","img":"Cooked Stambulb","parts":[["Item_PlantGet_S"]],"single":true,"book":18},
{"en":"Fried Wild Greens","ko":"야채구이","img":"Fried Wild Greens","parts":[["CookPlant"]],"single":true,"book":16},
{"en":"Simmered Tomato","ko":"토마토전골","img":"Simmered Tomato","parts":[["Item_Fruit_M"]],"single":true,"book":49},
{"en":"Simmered Fruit","ko":"과일전골","img":"Simmered Fruit","parts":[["CookFruit"]],"single":true,"book":47},
{"en":"Dubious Food","ko":"애매한 요리","img":"Dubious Food","parts":[["CookForeign"]],"single":true,"kind":"dubious","book":145},
{"en":"Dubious Food","ko":"애매한 요리","img":"Dubious Food","parts":[["CookGolem"]],"single":true,"kind":"dubious","book":145}],"critByTypes":[5.0,10.0,15.0,20.0,25.0],"elixir":{"ko":"물약","en":"Elixir"}}}};
  root.ZDATA = ZDATA;
  if (typeof module !== "undefined") module.exports = ZDATA;
})(typeof window !== "undefined" ? window : globalThis);
